Repository arco-design/arco-design, pull requests merged in 2021-11, with the labels that each got.

#89 fix: avatar group shows +x when maxCount equals 0
  components/Avatar/group.tsx
Labels: bug, enhancement

#107 feat: add trailColor to progress
  components/Progress/index.tsx
  components/Progress/interface.ts
  components/Progress/line-progess.tsx
  components/Progress/steps-progress.tsx
Labels: feature

#113 enhancement: DatePicker dayjs add fallback format
  components/DatePicker/__test__/format.test.tsx
  components/_util/dayjs.ts
Labels: enhancement

#110 feat: form supprot required symbol at the end of the label
  components/Form/README.en-US.md
  components/Form/README.zh-CN.md
  components/Form/form-item.tsx
  components/Form/interface.tsx
  stories/components/Form.jsx
Labels: feature

#120 style: fix table border and cell border when group header columns
  components/Table/style/index.less
Labels: component style

#116 fix: InputNumber should NOT show error status when given a value with wrong precision
  components/InputNumber/index.tsx
Labels: bug

#119 fix: When pagination current and pageSize are both controlled, curren…
  components/Pagination/interface.ts
  components/Pagination/pagination.tsx
  stories/components/Table.jsx
Labels: bug

#121 feat(image): support pressing `ESC` to close the preview
  components/Image/README.en-US.md
  components/Image/README.zh-CN.md
  components/Image/__test__/preview.test.tsx
  components/Image/image-preview.tsx
  components/Image/interface.ts
Labels: feature

#128 fix: The site page title compatible mobile media
  site/src/style/page.less
Labels: documentation

#149 fix: Trigger prevents mouse events before entered
  components/Trigger/index.tsx
Labels: bug

#145 fix: Menu.SubMenu's property priority is wrong
  components/Menu/__test__/index.test.tsx
  components/Menu/item-group.tsx
  components/Menu/item.tsx
  components/Menu/sub-menu/inline.tsx
  components/Menu/util.ts
  components/Progress/interface.ts
  components/Progress/line-progess.tsx
Labels: bug

#140 style: fix Table column align right + filter
  components/Table/style/index.less
Labels: component style

#151 style: MenuItem hide text after icon when Menu is collapsed
  components/Menu/style/index.less
Labels: component style

#150 style: Tooltip dark mode add border
  components/Tooltip/style/index.less
Labels: component style

#148 enhancement: Select allow user to define popup's max height in css files
  components/Select/option.tsx
  components/Select/select.tsx
Labels: bug, enhancement

#167 feat: add prop escToClose in Trigger
  components/Popconfirm/index.tsx
  components/Popconfirm/interface.ts
  components/Tooltip/index.tsx
  components/Tooltip/interface.ts
  components/Trigger/README.en-US.md
  components/Trigger/README.zh-CN.md
  components/Trigger/index.tsx
  components/Trigger/interface.ts
Labels: feature

#179 docs: select typo and demo fix
  components/Select/__demo__/custom-trigger.md
  components/Select/__demo__/group.md
Labels: documentation

#161 style(image): set the max size of error to fit parent
  components/Image/__test__/__snapshots__/demo.test.ts.snap
  components/Image/image.tsx
  components/Image/style/image.less
Labels: enhancement

#175 fix: trailColor does not work on CircleProgress
  components/Progress/__demo__/trailColor.md
  components/Progress/__test__/__snapshots__/demo.test.ts.snap
  components/Progress/__test__/index.test.tsx
  components/Progress/index.tsx
  components/Progress/steps-progress.tsx
Labels: bug

#186 style: Button horizontal padding change to 15px
  components/Button/style/token.less
Labels: component style

#185 feat: Form rules message support ReactNode
  components/Form/interface.tsx
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  package.json
  yarn.lock
Labels: feature

#181 feat: Carousel add propery icons to customize icon in arrows
  components/Carousel/README.en-US.md
  components/Carousel/README.zh-CN.md
  components/Carousel/__test__/index.test.tsx
  components/Carousel/arrow.tsx
  components/Carousel/index.tsx
  components/Carousel/interface.ts
Labels: feature

#170 fix(steps-progress): step active display error because calculation
  components/Progress/steps-progress.tsx
Labels: bug

#169 feat(resizebox): add onPaneResize to ResizeBox.Split
  components/ResizeBox/__test__/index.test.tsx
  components/ResizeBox/interface.ts
  components/ResizeBox/split.tsx
Labels: feature

#188 fix: ResizeObserver can not get latest react state in onResize callback
  components/_util/resizeObserver.tsx
Labels: bug

#180 feat: Dropdown allows the return value of onClickMenuItem to determine whether to automatically hide the menu
  components/Dropdown/__demo__/control.md
  components/Dropdown/__test__/__snapshots__/demo.test.ts.snap
  components/Dropdown/__test__/index.test.tsx
  components/Dropdown/index.tsx
  components/Menu/README.en-US.md
  components/Menu/README.zh-CN.md
  components/Menu/interface.tsx
  components/Select/__demo__/group.md
  components/_class/VirtualList/index.tsx
Labels: feature

#191 feat: Typography support cssEllipsis in simple ellipsis scene.
  components/Typography/README.en-US.md
  components/Typography/README.zh-CN.md
  components/Typography/__test__/__snapshots__/demo.test.ts.snap
  components/Typography/base.tsx
  components/Typography/interface.tsx
  components/Typography/style/index.less
  components/Typography/utils.tsx
  stories/components/Typography.jsx
Labels: feature

#182 style: Table virtualized scroll bar style
  components/Table/interface.tsx
  components/Table/table.tsx
  components/Table/tbody/index.tsx
Labels: component style

#183 feat: InputTag add property saveOnBlur
  components/InputTag/README.en-US.md
  components/InputTag/README.zh-CN.md
  components/InputTag/__demo__/labelInValue.md
  components/InputTag/__demo__/render-tag.md
  components/InputTag/__demo__/save-on-blur.md
  components/InputTag/__demo__/validate.md
  components/InputTag/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/__test__/index.test.tsx
  components/InputTag/input-tag.tsx
  components/InputTag/interface.ts
Labels: feature

#187 feat: Tabs add the scrollAfterEdit and scrollPosition properties
  components/Card/__test__/__snapshots__/demo.test.ts.snap
  components/Tabs/README.en-US.md
  components/Tabs/README.zh-CN.md
  components/Tabs/__demo__/scrollPosition.md
  components/Tabs/__test__/__snapshots__/demo.test.ts.snap
  components/Tabs/__test__/__snapshots__/index.test.tsx.snap
  components/Tabs/interface.ts
  components/Tabs/tab-header/index.tsx
  components/Tabs/tabs.tsx
  stories/components/Tab.jsx
Labels: feature

#190 feat: Form supports validateTrigger and validateLevel
  components/Form/__demo__/validateLevel.md
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/form.test.tsx
  components/Form/__test__/useform.test.tsx
  components/Form/__test__/validate.test.tsx
  components/Form/control.tsx
  components/Form/form-item.tsx
  components/Form/form-label.tsx
  components/Form/interface.tsx
  components/Form/store.tsx
  components/Form/style/status.less
  components/Form/utils.tsx
Labels: feature

#225 fix: Tabs bug React does not recognize the scrollPosition porp on a DOM element
  components/Card/__test__/__snapshots__/demo.test.ts.snap
  components/Tabs/__test__/__snapshots__/demo.test.ts.snap
  components/Tabs/__test__/__snapshots__/index.test.tsx.snap
  components/Tabs/tabs.tsx
  stories/components/Typography.jsx
Labels: bug

#223 enhancement: AutoComplete onPressEnter add a new parameter activeOption
  components/AutoComplete/index.tsx
  components/AutoComplete/interface.ts
Labels: enhancement

#230 fix: the timing of tree onExpandEnd trigger
  components/Tree/animation.tsx
Labels: bug

#235 fix: Anchor's scrollContainer should be added to Affix
  components/Anchor/__test__/index.test.tsx
  components/Anchor/anchor.tsx
Labels: bug
