Repository arco-design/arco-design, pull requests merged in 2021-12, with the labels that each got.

#250 fix: 事件绑定在icon上，hover时候点击边缘位置时，无法清空value。应绑定在icon外层的icon-hover的上
  components/Input/input-element.tsx
Labels: bug

#257 fix: Select callback's parameter enhancement when labelInValue is true
  components/Select/README.en-US.md
  components/Select/README.zh-CN.md
  components/Select/interface.tsx
  components/Select/select.tsx
  components/Select/utils.tsx
Labels: bug

#263 style: Menu icon color transition of selected items
  components/Menu/style/index.less
Labels: component style

#260 feat: drawer supports okButtonProps & cancelButtonProps
  components/Drawer/README.en-US.md
  components/Drawer/README.zh-CN.md
  components/Drawer/index.tsx
  components/Drawer/interface.ts
Labels: feature

#258 enhancement: trigger computed children dom
  components/Trigger/index.tsx
Labels: enhancement

#256 feat: SelectView add new property clearIcon
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Select/README.en-US.md
  components/Select/README.zh-CN.md
  components/TreeSelect/README.en-US.md
  components/TreeSelect/README.zh-CN.md
  components/_class/select-view.tsx
Labels: feature

#265 doc: update document for material market
  site/docs/material/advanced.team-site.en-US.md
  site/docs/material/advanced.team-site.zh-CN.md
  site/docs/material/init.config.en-US.md
  site/docs/material/init.config.zh-CN.md
  site/docs/material/init.template.en-US.md
Labels: documentation

#266 fix: typography 折叠判断镜像dom的setAttribute style 错误
  components/Typography/utils.tsx
Labels: bug

#264 feat: tag supports bordered prop
  components/Tag/README.en-US.md
  components/Tag/README.zh-CN.md
  components/Tag/__demo__/bordered.md
  components/Tag/__test__/__snapshots__/demo.test.ts.snap
  components/Tag/index.tsx
  components/Tag/interface.ts
  components/Tag/style/index.less
  components/Tag/style/token.less
Labels: feature

#270 fix: List scrollLoading not works when it's virtual
  components/List/index.tsx
Labels: bug

#282 fix: Form validate status bug
  components/Form/__test__/validate.test.tsx
  components/Form/control.tsx
  components/Form/form-item.tsx
  components/Form/interface.tsx
  components/Form/style/status.less
Labels: bug

#275 fix: Upload directory not work when drop is true
  components/Upload/__test__/drop.test.tsx
  components/Upload/trigger-node.tsx
Labels: bug

#306 fix: customeRequest can not be aborted
  components/Anchor/style/index.less
  components/Upload/upload.tsx
  components/Upload/uploader.tsx
Labels: bug

#302 style: Table indent cell style
  components/Table/__test__/__snapshots__/demo.test.ts.snap
  components/Table/style/index.less
  components/Table/tbody/td.tsx
  components/Tag/__demo__/close-async.md
  components/Tag/index.tsx
  site/docs/start.en-US.md
  site/docs/start.zh-CN.md
Labels: component style

#309 fix: cascader value repeat when changeOnSelect is true
  components/Cascader/panel/list.tsx
Labels: bug

#307 docs: fix table-'Header Fixed' no effect in most screens
  components/Table/__demo__/attribution.md
Labels: documentation

#301 fix: Typography locale config effect ellipsis , multiple children
  components/Typography/base.tsx
  components/Typography/edit-content.tsx
  components/Typography/interface.tsx
  components/Typography/operations.tsx
  components/Typography/utils.tsx
  stories/components/Typography.jsx
Labels: bug

#305 fix: slider onAfterChange value not update
  components/Slider/index.tsx
  components/Typography/interface.tsx
Labels: bug

#312 enhance: DatePicker select range
  components/DatePicker/hooks/useCellClassName.ts
  components/DatePicker/picker-range.tsx
Labels: enhancement

#325 feat: InputTag enable user darg of its values
  components/InputTag/README.en-US.md
  components/InputTag/README.zh-CN.md
  components/InputTag/__demo__/draggable.md
  components/InputTag/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/input-tag.tsx
  components/InputTag/interface.ts
  components/InputTag/style/index.less
  components/Select/README.en-US.md
  components/Select/README.zh-CN.md
  components/Select/__demo__/darggable.md
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/Select/select.tsx
  components/_class/Draggable/index.tsx
  components/_class/Draggable/interface.ts
  components/_class/Draggable/item.tsx
  components/_class/Draggable/style/index.less
  components/_class/select-view.tsx
  stories/components/Draggable.jsx
  stories/components/InputTag.jsx
  stories/components/Select.jsx
  stories/index.stories.js
Labels: feature

#330 style: fix InputTag style in FormItem with validateStatus
  components/Form/style/status.less
Labels: component style

#326 enhancement: InputNumber can receive all InputHTMLAttributes from its properties
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/InputNumber/index.tsx
  components/InputNumber/interface.ts
Labels: enhancement

#328 feat: typography onExpand params add click event
  components/Typography/README.en-US.md
  components/Typography/README.zh-CN.md
  components/Typography/__test__/index.test.tsx
  components/Typography/base.tsx
  components/Typography/interface.tsx
Labels: feature

#331 feat: tree supports halfCheckedKeys
  components/Tree/README.en-US.md
  components/Tree/README.zh-CN.md
  components/Tree/__demo__/loadmore.md
  components/Tree/__test__/index.test.tsx
  components/Tree/index.tsx
  components/Tree/interface.ts
Labels: feature

#334 feat: add expandProps.strictTreeData
  components/Table/README.en-US.md
  components/Table/README.zh-CN.md
  components/Table/__test__/common/data.ts
  components/Table/__test__/expand.test.tsx
  components/Table/interface.tsx
  components/Table/tbody/tr.tsx
Labels: feature

#327 feat: resizebox add a new sub-component `Resizebox.SplitGroup`
  components/Layout/__test__/__snapshots__/demo.test.ts.snap
  components/ResizeBox/README.en-US.md
  components/ResizeBox/README.zh-CN.md
  components/ResizeBox/__demo__/splitGroup.md
  components/ResizeBox/__test__/__snapshots__/demo.test.ts.snap
  components/ResizeBox/__test__/__snapshots__/index.test.tsx.snap
  components/ResizeBox/__test__/group.test.tsx
  components/ResizeBox/__test__/index.test.tsx
  components/ResizeBox/index.tsx
  components/ResizeBox/interface.ts
  components/ResizeBox/resize-trigger.tsx
  components/ResizeBox/split-group.tsx
  components/ResizeBox/style/index.less
  components/ResizeBox/style/token.less
  components/Typography/README.en-US.md
  components/Typography/README.zh-CN.md
  stories/components/Resizebox.jsx
  stories/index.stories.js
Labels: feature

#336 style: fix upload list margin
  components/Upload/style/index.less
Labels: component style

#329 fix: Recalculate the current page number when the data length changes
  components/Table/table.tsx
  stories/components/Table.jsx
Labels: feature

#339 fix(modal): fix when the modal visible value is true, locale config does not work
  components/ConfigProvider/index.tsx
  components/Modal/confirm.tsx
  components/Modal/locale.tsx
  components/Modal/modal.tsx
Labels: bug

#355 enhancement: SubMenu inline support selectable
  components/Menu/README.en-US.md
  components/Menu/README.zh-CN.md
  components/Menu/__test__/index.test.tsx
  components/Menu/interface.tsx
  components/Menu/sub-menu/inline.tsx
Labels: enhancement

#357 fix: upload read directory files by DirectoryReader limit maximum files
  components/Upload/__test__/drop.test.tsx
  components/Upload/style/index.less
  components/Upload/style/token.less
  components/Upload/trigger-node.tsx
  components/Upload/util.tsx
Labels: bug

#359 fix: Select without visible option list should clear input text after…
  components/Select/select.tsx
Labels: bug

#361 fix: TimePicker control mode set to undefined, next time not trigger …
  components/TimePicker/__test__/index.test.tsx
  components/TimePicker/picker.tsx
Labels: bug

#379 enhancement(divider): use flex to replace absolute style
  components/Button/__test__/__snapshots__/demo.test.ts.snap
  components/Divider/__test__/__snapshots__/demo.test.ts.snap
  components/Divider/index.tsx
  components/Divider/style/index.less
  components/Grid/__test__/__snapshots__/demo.test.ts.snap
  components/ResizeBox/__test__/__snapshots__/demo.test.ts.snap
Labels: component style

#373 fix: Select allowCreate may change disabled options by user input
  components/Select/__test__/index.test.tsx
  components/Select/select.tsx
Labels: bug

#381 chore: add compute-scroll-into-view to package dependencies
  package.json
Labels: bug

#380 fix: Slider should render the DOM in the same order as UI display
  components/Divider/style/index.less
  components/Slider/README.en-US.md
  components/Slider/README.zh-CN.md
  components/Slider/__test__/index.test.tsx
  components/Slider/index.tsx
  components/Slider/interface.tsx
Labels: bug

#382 fix: Table filter control mode set filteredValue to undefined to reset
  components/Table/__test__/filter.test.tsx
  components/Table/table.tsx
Labels: bug
