Repository arco-design/arco-design, pull requests merged in 2022-12, with the labels that each got.

#1627 fix(Pagination): defaultPageSize not working in sizeOptions
  components/Pagination/__test__/index.test.tsx
  components/Pagination/pagination.tsx
Labels: 🐛 bug

#1628 fix: modal hook
  components/Modal/__test__/useModal.test.tsx
  components/Modal/useModal/hookModal.tsx
  components/Modal/useModal/index.tsx
Labels: 🐛 bug

#1631 fix: 修复date-picker周选择器对moment.js的兼容
  components/_util/dayjs.ts
Labels: 🐛 bug

#1639 fix(cascader): search result empty
  components/Cascader/panel/search-panel.tsx
Labels: 🐛 bug

#1641 style: Switch check animation fix
  components/Switch/style/index.less
Labels: 💅 component style

#1640 enhance: Select show dropdown-box when allowCreate and there is no user inputing
  components/Select/select.tsx
Labels: ⚡️ enhancement

#1638 enhancement: Form.List enhance
  components/Form/control.tsx
  components/Form/form-list.tsx
  components/Form/utils.tsx
Labels: ⚡️ enhancement

#1668 feat: datepicker supports prefix & timepicker supports prefix
  components/DatePicker/README.en-US.md
  components/DatePicker/README.zh-CN.md
  components/DatePicker/__demo__/month.md
  components/DatePicker/__demo__/prefix.md
  components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
  components/DatePicker/interface.tsx
  components/DatePicker/picker-range.tsx
  components/DatePicker/picker.tsx
  components/TimePicker/README.en-US.md
  components/TimePicker/README.zh-CN.md
  components/TimePicker/__demo__/prefix.md
  components/TimePicker/__test__/__snapshots__/demo.test.ts.snap
  components/TimePicker/interface.tsx
  components/TimePicker/picker.tsx
  components/_class/picker/input-range.tsx
  components/_class/picker/input.tsx
  components/_class/picker/style/index.less
  components/_class/picker/style/token.less
Labels: ✨ feature

#1666 fix: collapse can not work in react 18 strictmode
  components/Collapse/collapse.tsx
Labels: 🐛 bug

#1665 feat: Form.Item supports tooltip props
  components/Form/README.en-US.md
  components/Form/README.zh-CN.md
  components/Form/__demo__/layout.md
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Form/form-item.tsx
  components/Form/form-label.tsx
  components/Form/interface.tsx
  components/Form/style/index.less
  components/Form/style/token.less
Labels: ✨ feature

#1669 fix: upload filter logic
  components/Upload/util.tsx
Labels: 🐛 bug

#1652 enhance: trigger should keep position
  components/Trigger/index.tsx
Labels: ⚡️ enhancement

#1687 enhancement: remove defaultProps from function component
  .github/workflows/deploy-site-preview.yml
  components/Carousel/arrow.tsx
  components/DatePicker/index.tsx
  components/DatePicker/panels/date/index.tsx
  components/DatePicker/panels/month/index.tsx
  components/DatePicker/panels/quarter/index.tsx
  components/DatePicker/panels/range/index.tsx
  components/DatePicker/panels/week/index.tsx
  components/DatePicker/panels/year/index.tsx
  components/DatePicker/picker.tsx
  components/Dropdown/index.tsx
  components/Input/password.tsx
  components/Layout/index.tsx
  components/Layout/sider.tsx
  components/Menu/index.tsx
  components/Progress/line-progess.tsx
  components/Progress/steps-progress.tsx
  components/Select/opt-group.tsx
  components/Select/option.tsx
  components/Select/utils.tsx
  components/Statistic/countdown.tsx
  components/Table/summary/cell.tsx
  components/Table/summary/row.tsx
  components/_class/Draggable/index.tsx
  components/_class/Draggable/item.tsx
  components/index.tsx
Labels: ⚡️ enhancement

#1689 fix(Input): defaultValue not work in react18 strictmode
  components/_util/hooks/useMergeValue.ts
Labels: 🐛 bug, React 18

#1676 fix: update anchor element in-view judgment logic
  components/Anchor/anchor.tsx
Labels: 🐛 bug
