Repository arco-design/arco-design, pull requests merged in 2022-09, with the labels that each got.

#1358 fix: DatePicker locale de-DE error
  components/locale/de-DE.tsx
Labels: 🐛 bug

#1344 site: remove site redirect
  site/src/App.js
  site/src/utils/i18n.js
Labels: 📖 documentation

#1365 fix: Cascader panel list scrolling
  components/Cascader/panel/list.tsx
  components/_class/VirtualList/index.tsx
Labels: 🐛 bug

#1366 fix(Typography): shakes obviously during calculation
  components/Typography/useCssEllipsis.tsx
  components/Typography/useEllipsis.tsx
Labels: 🐛 bug

#1354 fix(Cascader): Parent node cannot switch from half-selected to unselected when there are disabled children
  components/Cascader/__test__/case.test.tsx
  components/Cascader/base/node.ts
  components/Cascader/util.tsx
Labels: 🐛 bug

#1364 fix(Steps): Step onClick not triggered
  components/Steps/README.en-US.md
  components/Steps/README.zh-CN.md
  components/Steps/index.tsx
  components/Steps/interface.ts
  components/Steps/step.tsx
Labels: 🐛 bug

#1359 fix: focuslock default allow cross iframe
  components/Drawer/index.tsx
  components/Modal/modal.tsx
  components/Popconfirm/index.tsx
  package.json
  stories/Drawer.story.tsx
  yarn.lock
Labels: 🐛 bug

#1367 enhancement: avoid createRoot warning
  components/Message/index.tsx
  components/Modal/confirm.tsx
  components/Notification/index.tsx
  components/_util/react-dom.ts
Labels: ⚡️ enhancement, React 18

#1357 fix: disabled InputTag should also show placeholder
  components/Input/input-element.tsx
  components/InputTag/style/index.less
Labels: 🐛 bug

#1362 style: enhance style of <a> in Menu.Item
  components/Dropdown/style/index.less
  components/Menu/style/index.less
Labels: ⚡️ enhancement

#1373 fix: 修复body设置flex之后message不显示的问题
  components/Message/style/index.less
Labels: 🐛 bug

#1368 update: 修复type=capsule下Tabs disabled option仍有hover效果
  components/Tabs/style/index.less
Labels: 💅 component style

#1390 enhance: DatePicker.RangePicker fix show dates
  components/DatePicker/panels/range/index.tsx
  components/DatePicker/picker-range.tsx
Labels: ⚡️ enhancement

#1363 feat: breadcrumb support link tagName click
  components/Breadcrumb/README.en-US.md
  components/Breadcrumb/README.zh-CN.md
  components/Breadcrumb/__test__/index.test.tsx
  components/Breadcrumb/interface.ts
  components/Breadcrumb/item.tsx
  components/Breadcrumb/style/index.less
  stories/Breadcrumb.story.tsx
Labels: ✨ feature

#1398 enhancement: update validate messages
  components/_util/react-dom.ts
  components/locale/en-US.tsx
  components/locale/zh-CN.tsx
  package.json
  yarn.lock
Labels: ⚡️ enhancement

#1360 feat: support onKeyDown callback for Select/TreeSelect/Cascader
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Cascader/__test__/index.test.tsx
  components/Cascader/cascader.tsx
  components/Select/README.en-US.md
  components/Select/README.zh-CN.md
  components/Select/__test__/index.test.tsx
  components/Select/select.tsx
  components/TreeSelect/README.en-US.md
  components/TreeSelect/README.zh-CN.md
  components/TreeSelect/__test__/index.test.tsx
  components/TreeSelect/tree-select.tsx
  components/_class/select-view.tsx
Labels: ✨ feature

#1388 enhancement: Statistic skip rendering dom of prefix when suffix is null/undefined
  components/Statistic/__test__/__snapshots__/demo.test.ts.snap
  components/Statistic/index.tsx
Labels: 💅 component style

#1393 enhance: avoid Space item mount again caused by react-key overwrite
  components/Space/index.tsx
Labels: ⚡️ enhancement

#1397 feat: Form supports dependencies
  components/Form/__demo__/register.md
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/case.test.tsx
  components/Form/__test__/dym.test.tsx
  components/Form/__test__/form.test.tsx
  components/Form/__test__/index.test.tsx
  components/Form/__test__/list.test.tsx
  components/Form/__test__/provider.test.tsx
  components/Form/__test__/shouldUpdate.test.tsx
  components/Form/__test__/use.test.tsx
  components/Form/__test__/validate.test.tsx
  components/Form/control.tsx
  components/Form/interface.tsx
  components/Form/utils.tsx
  components/_util/warning.ts
  components/index.tsx
Labels: ✨ feature

#1396 feat: Grid support responsive size xxxl
  components/Grid/README.en-US.md
  components/Grid/README.zh-CN.md
  components/Grid/col.tsx
  components/Grid/interface.ts
  components/Grid/row.tsx
  components/Grid/style/col.less
  components/Layout/README.en-US.md
  components/Layout/README.zh-CN.md
  components/Layout/interface.ts
  components/List/README.en-US.md
  components/List/README.zh-CN.md
  components/List/interface.ts
  components/_util/responsiveObserve.ts
Labels: ✨ feature

#1391 style: avoid Layout overflow caused by border
  components/Layout/style/index.less
Labels: 💅 component style

#1389 feat: Transfer support passing in different properties to source/targ…
  components/Transfer/README.en-US.md
  components/Transfer/README.zh-CN.md
  components/Transfer/__test__/index.test.tsx
  components/Transfer/index.tsx
  components/Transfer/interface.tsx
Labels: ✨ feature

#1401 feat: support useMessage, useNotification
  components/ConfigProvider/README.en-US.md
  components/ConfigProvider/README.zh-CN.md
  components/ConfigProvider/__demo__/local-setting.md
  components/ConfigProvider/__demo__/rtl.md
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/ConfigProvider/index.tsx
  components/ConfigProvider/interface.ts
  components/Message/__demo__/useMessage.md
  components/Message/__test__/__snapshots__/demo.test.ts.snap
  components/Message/__test__/useMessage.test.tsx
  components/Message/index.tsx
  components/Message/useMessage.tsx
  components/Modal/useModal/index.tsx
  components/Notification/__demo__/useNotification.md
  components/Notification/__test__/__snapshots__/demo.test.ts.snap
  components/Notification/__test__/useNotification.test.tsx
  components/Notification/index.tsx
  components/Notification/useNotification.tsx
  components/_class/notification.tsx
  components/_util/contextHolder.tsx
Labels: ✨ feature

#1400 fix: form watch value not work when field change
  components/Form/__test__/case.test.tsx
  components/Form/__test__/validate.test.tsx
  components/Form/hooks/useWatch.ts
Labels: 🐛 bug

#1418 fix: the bug that the holderRef of useModal may not exist
  components/ConfigProvider/__demo__/local-setting.md
  components/Modal/useModal/index.tsx
Labels: 🐛 bug

#1419 enhance: The previewable image mouseover style changes to zoom-out
  components/Image/image.tsx
  components/Image/style/image.less
Labels: 💅 component style

#1420 fix: Table getRowKey throw error when the record is not found
  components/Table/utils.tsx
Labels: 🐛 bug

#1437 fix: popconfirm focuslock
  components/Popconfirm/index.tsx
Labels: 🐛 bug

#1433 style: Sub table in table expand content, cell color error
  components/Table/style/index.less
Labels: 💅 component style

#1440 fix: modal unmount error in react18
  components/Modal/confirm.tsx
  components/_util/react-dom.ts
  stories/Modal.story.tsx
Labels: 🐛 bug
