Repository arco-design/arco-design, pull requests merged in 2022-03, with the labels that each got.

#560 fix: calendar today outline
  components/Calendar/style/index.less
Labels: bug

#588 feat(Image): support users to manually pass in the preview index
  components/Image/__test__/preview.test.tsx
  components/Image/image-preview.tsx
  components/Image/image.tsx
  components/Image/interface.ts
  components/Image/utils/getScale.ts
  stories/components/Image.jsx
Labels: feature

#609 fix(table): placeholder can apply if the data is an empty string or null
  components/Table/__test__/columns.test.tsx
  components/Table/tbody/td.tsx
Labels: enhancement

#608 fix[tree-select]: input can not be focused
  components/Tree/index.tsx
  components/Tree/interface.ts
  components/Tree/node-list.tsx
  components/TreeSelect/tree-list.tsx
  components/TreeSelect/tree-select.tsx
Labels: bug

#607 feat: Form supports Form.Provider
  components/Form/README.en-US.md
  components/Form/README.zh-CN.md
  components/Form/__demo__/form-provider.md
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/provider.test.tsx
  components/Form/context.ts
  components/Form/form-provider.tsx
  components/Form/form.tsx
  components/Form/index.tsx
  components/Form/interface.tsx
Labels: feature

#599 fix: cascader parameter error
  components/Cascader/__test__/index.test.tsx
  components/Cascader/cascader.tsx
  components/Cascader/util.tsx
Labels: bug

#613 enhancement: Transfer shound only handle filtered items when check/uncheck all
  components/Transfer/__test__/index.test.tsx
  components/Transfer/index.tsx
  components/Transfer/interface.tsx
  components/Transfer/list.tsx
  stories/components/Transfer.jsx
Labels: enhancement

#614 feat(tree): allowDrop supports dragNode
  components/Tree/README.en-US.md
  components/Tree/README.zh-CN.md
  components/Tree/index.tsx
  components/Tree/interface.ts
Labels: feature

#627 enhance: DatePicker page show dates not change when select
  components/DatePicker/picker-range.tsx
Labels: enhancement

#628 fix: VirtualList scrollIntoView is invalid to elements in the first …
  components/_class/VirtualList/index.tsx
Labels: 🐛 bug

#633 fix: cascader lost label text when onSearch & defaultValue
  components/Cascader/cascader.tsx
Labels: 🐛 bug

#647 fix: DatePicker.RangePicker separator not work
  components/DatePicker/__test__/range.test.tsx
  components/DatePicker/picker-range.tsx
Labels: 🐛 bug

#650 fix: Table virtualized column align right not work
  components/Table/style/index.less
Labels: 🐛 bug

#651 fix(input-tag): fix InputTag display cleat button when set allowClear and readOnly together
  components/InputTag/__test__/index.test.tsx
  components/InputTag/input-tag.tsx
Labels: 🐛 bug

#670 enhance: Tooltip add role="tooltip"
  components/Tooltip/index.tsx
Labels: ⚡️ enhancement

#678 feat: Table support sort tree data
  components/Table/__test__/common/data.ts
  components/Table/__test__/sorter.test.tsx
  components/Table/table.tsx
Labels: ✨ feature

#687 fix: DatePicker disabledDate #421
  components/DatePicker/__demo__/disabled-date.md
  components/DatePicker/__test__/panel.test.tsx
  components/DatePicker/panels/body.tsx
  components/DatePicker/panels/date/index.tsx
  components/DatePicker/panels/month/index.tsx
  components/DatePicker/panels/quarter/index.tsx
  components/DatePicker/panels/year/index.tsx
  components/DatePicker/util.ts
Labels: 🐛 bug

#685 style: input clear icon disply
  components/Input/style/index.less
Labels: 💅 component style

#684 feat: typography click callback add event params
  components/Typography/README.en-US.md
  components/Typography/README.zh-CN.md
  components/Typography/base.tsx
  components/Typography/interface.tsx
  components/Typography/operations.tsx
Labels: ✨ feature

#683 style: When the Slider component passes in marks, the head and tail e…
  components/Slider/__test__/__snapshots__/demo.test.ts.snap
  components/Slider/dots.tsx
  components/Slider/hooks/useInterval.ts
  components/Slider/index.tsx
Labels: 💅 component style

#688 fix: List render's parameter:index has a wrong value when grid is true
  components/List/index.tsx
  components/Spin/README.en-US.md
  components/Spin/README.zh-CN.md
  components/Spin/interface.ts
Labels: 🐛 bug

#690 style: zoom.less add import default theme
  components/style/animation/zoom.less
Labels: 💅 component style

#655 fix: slider对于小数step的支持
  components/Slider/__test__/__snapshots__/demo.test.ts.snap
  components/Slider/hooks/useInterval.ts
  components/Slider/hooks/useLegalValue.ts
  components/Slider/index.tsx
  stories/components/Slider.jsx
Labels: 🐛 bug

#686 feat: [Select, TreeSelect, AutoComplete] triggerElement support render-function
  components/AutoComplete/README.en-US.md
  components/AutoComplete/README.zh-CN.md
  components/AutoComplete/index.tsx
  components/AutoComplete/interface.ts
  components/List/__test__/index.test.tsx
  components/Select/README.en-US.md
  components/Select/README.zh-CN.md
  components/Select/__test__/index.test.tsx
  components/Select/interface.tsx
  components/Select/select.tsx
  components/TreeSelect/README.en-US.md
  components/TreeSelect/README.zh-CN.md
  components/TreeSelect/interface.ts
  components/TreeSelect/tree-select.tsx
  scripts/jest.config.js
Labels: ✨ feature

#692 feat: cascader supports checkedStrategy
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Cascader/__demo__/multiple.md
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/__test__/index.test.tsx
  components/Cascader/base/node.ts
  components/Cascader/base/store.ts
  components/Cascader/cascader.tsx
  components/Cascader/interface.ts
  components/Cascader/util.tsx
Labels: ✨ feature

#696 fix: issue #695
  components/Table/style/index.less
Labels: 💅 component style

#702 Accessibility message
  components/Message/__test__/__snapshots__/index.test.tsx.snap
  components/Notification/__test__/__snapshots__/index.test.tsx.snap
  components/_class/notice.tsx
Labels: ⚡️ enhancement

#701 enhance: Docs page some button add aria-label
  site/src/page.js
  site/src/widget/ThemeBox/index.tsx
Labels: ⚡️ enhancement

#704 enhance: Tag and Modal close button add role and aria-label
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/__test__/__snapshots__/demo.test.ts.snap
  components/Modal/modal.tsx
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/Tag/__test__/__snapshots__/demo.test.ts.snap
  components/Tag/index.tsx
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/Trigger/__test__/__snapshots__/demo.test.ts.snap
Labels: ⚡️ enhancement

#712 enhance: Pagination step button add aria-label
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/List/__test__/__snapshots__/demo.test.ts.snap
  components/Pagination/__test__/__snapshots__/demo.test.ts.snap
  components/Pagination/__test__/__snapshots__/index.test.tsx.snap
  components/Pagination/page-item.tsx
  components/Pagination/page-options.tsx
  components/Table/__test__/__snapshots__/demo.test.ts.snap
  components/Transfer/__test__/__snapshots__/demo.test.ts.snap
  components/locale/de-DE.tsx
  components/locale/en-US.tsx
  components/locale/es-ES.tsx
  components/locale/fr-FR.tsx
  components/locale/id-ID.tsx
  components/locale/it-IT.tsx
  components/locale/ja-JP.tsx
  components/locale/ko-KR.tsx
  components/locale/th-TH.tsx
  components/locale/zh-CN.tsx
  components/locale/zh-HK.tsx
  components/locale/zh-TW.tsx
Labels: ⚡️ enhancement
