Repository arco-design/arco-design, pull requests merged in 2022-11, with the labels that each got.

#1534 style: select-view style forward compatibility and solve baseline issue
  components/Select/style/mixin.less
Labels: 💅 component style

#1540 fix: DatePicker.RangePicker and TimePicker.RangePicker press tab to s…
  components/DatePicker/picker-range.tsx
  components/TimePicker/picker.tsx
Labels: 🐛 bug

#1558 enhance: Modal,Drawer,Popconfirm okText and cancelText support ReactNode
  components/Drawer/README.en-US.md
  components/Drawer/README.zh-CN.md
  components/Drawer/interface.ts
  components/Modal/README.en-US.md
  components/Modal/README.zh-CN.md
  components/Modal/interface.ts
  components/Popconfirm/README.en-US.md
  components/Popconfirm/README.zh-CN.md
  components/Popconfirm/interface.ts
Labels: ⚡️ enhancement

#1564 fix: the `Layout.Sider` would flicker for the first rendering when `collapsed` is enabled by default
  components/Layout/sider.tsx
Labels: 🐛 bug

#1561 enhance: VirtualList performance while scrolling near the list bottom
  components/_class/VirtualList/index.tsx
Labels: ⚡️ enhancement

#1562 enhance: Table column.render optimization
  components/Table/tbody/td.tsx
Labels: ⚡️ enhancement

#1559 enhance: InputNumber keep cursor position while user typing
  components/InputNumber/index.tsx
  components/InputNumber/useSelectionRange.ts
Labels: ⚡️ enhancement

#1572 fix(upload): upload accept can receive upper file extensions
  components/Upload/util.tsx
Labels: 🐛 bug

#1580 fix: when panel open, change mode page show dates correctly
  components/DatePicker/__test__/range.test.tsx
  components/DatePicker/picker-range.tsx
Labels: 🐛 bug

#1581 style(Steps): label vertical placement
  components/Steps/style/circle.less
Labels: 💅 component style

#1611 fix: Table data is array of number or string, cause error
  components/Table/__test__/case.test.tsx
  components/Table/utils.tsx
Labels: 🐛 bug

#1612 fix: Tigger can not show popup when children is checkbox.group& radio…
  components/Checkbox/group.tsx
  components/Radio/group.tsx
Labels: 🐛 bug

#1614 fix(Tabs): addButton width causes inaccurate calculation of header sc…
  components/Tabs/tab-header/index.tsx
  stories/Tabs.story.tsx
Labels: 🐛 bug

#1603 feat: InputNumber support BigInt and strictMode
  components/InputNumber/Decimal.ts
  components/InputNumber/README.en-US.md
  components/InputNumber/README.zh-CN.md
  components/InputNumber/__demo__/strictMode.md
  components/InputNumber/__test__/__snapshots__/demo.test.ts.snap
  components/InputNumber/__test__/index.test.tsx
  components/InputNumber/index.tsx
  components/InputNumber/interface.ts
  components/InputNumber/utils.ts
  stories/InputNumber.story.tsx
Labels: ✨ feature

#1610 feat: Transfer add virtualListProps to turn on virtual-scrolling
  components/List/index.tsx
  components/Transfer/README.en-US.md
  components/Transfer/README.zh-CN.md
  components/Transfer/interface.tsx
  components/Transfer/list.tsx
Labels: ✨ feature

#1606 fix: containerScrollToClose not work
  components/Trigger/__test__/case.test.tsx
  components/Trigger/index.tsx
  components/_util/dom.ts
Labels: 🐛 bug

#1604 feat: drawer supports zindex property
  components/Drawer/README.en-US.md
  components/Drawer/README.zh-CN.md
  components/Drawer/index.tsx
  components/Drawer/interface.ts
  components/Radio/interface.ts
Labels: ✨ feature

#1569 fix: Select needs two clicks to show the popup when showSearch is true or allowCreate is true
  components/Select/style/mixin.less
Labels: 🐛 bug
