Repository arco-design/arco-design, pull requests merged in 2022-04, with the labels that each got.

#719 enhancement: Aria for Breadcrumb
  components/Breadcrumb/__test__/__snapshots__/demo.test.ts.snap
  components/Breadcrumb/__test__/__snapshots__/index.test.tsx.snap
  components/Breadcrumb/index.tsx
  components/Breadcrumb/item.tsx
  components/Layout/__test__/__snapshots__/demo.test.ts.snap
  components/PageHeader/__test__/__snapshots__/demo.test.ts.snap
Labels: ⚡️ enhancement

#718 enhancement: Transfer add aria-label
  components/Transfer/__test__/__snapshots__/demo.test.ts.snap
  components/Transfer/__test__/__snapshots__/index.test.tsx.snap
  components/Transfer/index.tsx
Labels: ⚡️ enhancement

#722 enhance: Aria for Menu
  components/Layout/__test__/__snapshots__/demo.test.ts.snap
  components/Menu/__test__/__snapshots__/demo.test.ts.snap
  components/Menu/__test__/__snapshots__/index.test.tsx.snap
  components/Menu/context.ts
  components/Menu/index.tsx
  components/Menu/interface.tsx
  components/Menu/item.tsx
  components/Menu/sub-menu/inline.tsx
  components/Menu/sub-menu/pop.tsx
Labels: ⚡️ enhancement

#694 enhancement(Timepicker): use not disabled value as default
  components/TimePicker/__test__/index.test.tsx
  components/TimePicker/time-picker.tsx
Labels: ⚡️ enhancement

#723 enhancement: List scrollLoading element position fix when it's virtual
  components/List/index.tsx
Labels: ⚡️ enhancement

#740 doc: update document for material market
  components/Select/__demo__/async-data.md
  site/docs/material/advanced.team-site.en-US.md
  site/docs/material/advanced.team-site.zh-CN.md
  site/docs/material/init.config.en-US.md
  site/docs/material/init.config.zh-CN.md
  site/docs/material/init.template.en-US.md
  site/docs/material/init.template.zh-CN.md
  site/docs/material/start.qa.en-US.md
  site/docs/material/start.qa.zh-CN.md
Labels: 📖 documentation

#769 fix: The onSelect event is not triggered when the TimePicker input is…
  components/TimePicker/picker.tsx
Labels: 🐛 bug

#763 fix(cascader): Search panel display error
  components/Cascader/panel/list.tsx
  components/Cascader/panel/search-panel.tsx
  components/Cascader/util.tsx
Labels: 🐛 bug

#756 enhance: 优化 getRowsFromKeys 性能, O(n^2) => O(n)
  components/Table/hooks/useRowSelection.tsx
Labels: ⚡️ enhancement

#765 fix: DatePicker.RangePicker utcOffset and timezone not work
  components/ConfigProvider/__demo__/component-config.md
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/DatePicker/__demo__/timezone.md
  components/DatePicker/__demo__/utcOffset.md
  components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
  components/DatePicker/picker-range.tsx
Labels: 🐛 bug

#760 fix(Form): onChange should be trigger when children is a function
  components/Form/control.tsx
Labels: 🐛 bug

#767 feat(pagination): support buffersize
  components/Pagination/README.en-US.md
  components/Pagination/__demo__/more-buffer.md
  components/Pagination/__test__/__snapshots__/demo.test.ts.snap
  components/Pagination/__test__/index.test.tsx
  components/Pagination/interface.ts
  components/Pagination/pagination.tsx
  stories/components/Pagination.jsx
Labels: ✨ feature

#753 fix: Checkbox children type
  components/Checkbox/interface.ts
Labels: ⚡️ enhancement

#771 feat(card): add style token
  components/Card/style/index.less
  components/Card/style/token.less
Labels: ✨ feature

#770 feat: Trigger supports updateAtScroll property
  components/Trigger/README.en-US.md
  components/Trigger/README.zh-CN.md
  components/Trigger/__demo__/updateAtScroll.md
  components/Trigger/__test__/__snapshots__/demo.test.ts.snap
  components/Trigger/index.tsx
  components/Trigger/interface.ts
  components/_util/dom.ts
Labels: ✨ feature

#772 fix(Typography): Does not enforce white-space overrides when calculating
  components/Typography/utils.tsx
Labels: 🐛 bug

#762 feat(Slider): showInput support InputNumberProps
  components/Slider/__demo__/input.md
  components/Slider/__demo__/interval.md
  components/Slider/__test__/__snapshots__/demo.test.ts.snap
  components/Slider/__test__/index.test.tsx
  components/Slider/index.tsx
  components/Slider/input.tsx
  components/Slider/interface.tsx
Labels: ✨ feature

#768 enhancement: VirtualList scrolling performance when height of list item varies greatly
  components/List/__demo__/virtual-list.md
  components/List/index.tsx
  components/Select/__demo__/custom-trigger.md
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/_class/VirtualList/index.tsx
Labels: ⚡️ enhancement, ✨ feature

#729 fix: Select.Option onMouseEnter/onMouseLeave not work
  components/Select/__test__/index.test.tsx
  components/Select/interface.tsx
  components/Select/option.tsx
  components/Select/select.tsx
Labels: 🐛 bug

#629 fix(modal): fix close modal with esc keydown event will close all
  components/Modal/__demo__/async_close.md
  components/Modal/__test__/index.test.tsx
  components/Modal/modal.tsx
Labels: ⚡️ enhancement

#796 enhancement: InputNumber with precision use Math.round to replace number.toFixed
  components/InputNumber/__test__/index.test.tsx
  components/InputNumber/index.tsx
  components/InputNumber/utils.ts
Labels: ⚡️ enhancement

#798 enhance: Pagination locale fallback to avoid error
  components/Pagination/page-item.tsx
  components/Pagination/pagination.tsx
Labels: ⚡️ enhancement

#801 fix: Fixed the issue that the Mentions Component was missing the notF…
  components/Mentions/index.tsx
Labels: 🐛 bug

#797 fix: notification count error
  components/_class/notification.tsx
Labels: 🐛 bug

#799 ts: TableProps rowKey
  components/Calendar/README.en-US.md
  components/Calendar/README.zh-CN.md
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Image/README.en-US.md
  components/Image/README.zh-CN.md
  components/Pagination/README.zh-CN.md
  components/Radio/interface.ts
  components/Slider/README.en-US.md
  components/Slider/README.zh-CN.md
  components/Table/README.en-US.md
  components/Table/README.zh-CN.md
  components/Table/interface.tsx
  components/Timeline/README.en-US.md
  components/Timeline/README.zh-CN.md
  components/Tree/README.zh-CN.md
  components/Typography/README.zh-CN.md
Labels: ⚡️ enhancement

#715 enhancement: Aria improvement for Select
  components/BackTop/__test__/__snapshots__/demo.test.ts.snap
  components/Calendar/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/__test__/__snapshots__/index.test.tsx.snap
  components/Cascader/cascader.tsx
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Input/__test__/__snapshots__/demo.test.ts.snap
  components/Pagination/__test__/__snapshots__/demo.test.ts.snap
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/Select/__test__/__snapshots__/index.test.tsx.snap
  components/Select/option.tsx
  components/Select/select.tsx
  components/Table/__test__/__snapshots__/demo.test.ts.snap
  components/TimePicker/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/tree-select.tsx
  components/Trigger/__test__/__snapshots__/demo.test.ts.snap
  components/_class/select-view.tsx
Labels: ⚡️ enhancement

#811 fix: timepicker error when showTime is an empty object
  components/DatePicker/__test__/date.test.tsx
  components/DatePicker/picker.tsx
Labels: 🐛 bug

#824 feat(i18n): locale support vi-vN
  components/ConfigProvider/__demo__/basic.md
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/locale/vi-VN.tsx
  site/docs/i18n.en-US.md
  site/docs/i18n.zh-CN.md
Labels: ✨ feature

#823 fix: form not work in react 18 strictmode
  components/Form/control.tsx
  components/Form/form-item.tsx
Labels: 🐛 bug

#820 fix: Menu should keep open keys after collapse/uncollapse
  components/Menu/__test__/index.test.tsx
  components/Menu/index.tsx
  components/Menu/sub-menu/index.tsx
  components/Menu/sub-menu/inline.tsx
Labels: 🐛 bug

#822 fix(Typography): white-space effect when ellipsis is calculated
  components/Typography/utils.tsx
Labels: 🐛 bug

#829 fix: switch onclick
  components/Switch/__test__/index.test.tsx
  components/Switch/index.tsx
  components/Switch/interface.ts
Labels: 🐛 bug

#819 fix(tabs):Fixed the bug that the timing of the tabs scroll button was incorrectly judged.
  components/Tabs/tab-header/index.tsx
Labels: 🐛 bug

#827 fix(Table): Table Pagination 优先级
  components/Table/__test__/pagination.test.tsx
  components/Table/table.tsx
Labels: 🐛 bug
