Repository arco-design/arco-design, pull requests merged in 2022-07, with the labels that each got.

#1070 fix: react warning caused by _ignorePropsFromGlobal
  components/Input/input.tsx
  components/Input/interface.tsx
  components/_util/hooks/useMergeProps.ts
Labels: 🐛 bug

#1079 fix: drawer should be hidden
  components/Drawer/index.tsx
Labels: 🐛 bug

#1080 fix: Error when Table data item is class
  components/Table/utils.tsx
  stories/Table.story.tsx
Labels: 🐛 bug

#1077 fix: clear error status
  components/Form/README.en-US.md
  components/Form/README.zh-CN.md
  components/Form/control.tsx
  components/Form/form-item.tsx
  components/Form/interface.tsx
Labels: 🐛 bug

#1074 fix: TimePicker with timezone auto sort
  components/TimePicker/picker.tsx
  components/TimePicker/util.ts
  stories/DatePicker.story.tsx
Labels: 🐛 bug

#1073 fix: add style for selected date when year mode
  components/Calendar/style/index.less
Labels: 🐛 bug

#1102 fix: form onchange
  components/Form/control.tsx
  components/Form/interface.tsx
  components/Form/utils.tsx
  stories/Form.story.tsx
Labels: 🐛 bug

#1103 style: hint style of draggable Transfer item
  components/Transfer/style/index.less
Labels: 💅 component style

#1106 style: Table no data border
  components/Table/__demo__/attribution.md
  components/Table/__test__/__snapshots__/demo.test.ts.snap
  components/Table/style/index.less
  components/Table/table.tsx
Labels: 💅 component style

#1104 fix: Error when Table data is null
  components/Table/table.tsx
  components/Table/utils.tsx
Labels: 🐛 bug

#1097 fix: upload should check file type before upload
  components/Upload/uploader.tsx
Labels: 🐛 bug

#1110 feat: InputTag validate allow return a non-boolean result
  components/InputTag/README.en-US.md
  components/InputTag/README.zh-CN.md
  components/InputTag/__demo__/basic.md
  components/InputTag/__demo__/validate.md
  components/InputTag/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/__test__/index.test.tsx
  components/InputTag/input-tag.tsx
  components/InputTag/interface.ts
  stories/InputTag.story.tsx
Labels: ✨ feature

#1109 style: add typography default whiteSpace style
  components/Typography/style/index.less
Labels: 💅 component style

#1034 feat: Form.useWatch supports multiple fields
  components/Form/__test__/use.test.tsx
  components/Form/hooks/useWatch.ts
Labels: ✨ feature

#1071 feat: add ondrop prop for upload
  components/Upload/README.en-US.md
  components/Upload/README.zh-CN.md
  components/Upload/__demo__/drag.md
  components/Upload/__test__/__snapshots__/demo.test.ts.snap
  components/Upload/interface.tsx
  components/Upload/trigger-node.tsx
  components/Upload/upload.tsx
  components/Upload/uploader.tsx
Labels: ✨ feature

#1030 RTL style: Avatar.
  components/Avatar/__demo__/autoFixFontSize.md
  components/Avatar/__test__/__snapshots__/demo.test.ts.snap
  components/Avatar/avatar.tsx
  components/Avatar/group.tsx
  components/Avatar/style/index.less
Labels: 💅 component style

#1032 RTL style: Badge.
  components/Badge/__demo__/animate.md
  components/Badge/__test__/__snapshots__/demo.test.ts.snap
  components/Badge/index.tsx
  components/Badge/style/index.less
  components/Badge/usage/index.en-US.md
  components/Badge/usage/index.zh-CN.md
Labels: 💅 component style

#1123 perf(lodash): lodash on demand
  components/_util/getHighlightText.tsx
Labels: ⚡️ enhancement

#1136 fix: disabled not work for the second button of Dropdown.Button
  components/Dropdown/__test__/__snapshots__/demo.test.ts.snap
  components/Dropdown/__test__/index.test.tsx
  components/Dropdown/button.tsx
  components/Dropdown/index.tsx
  components/Link/__demo__/dropdown.md
  components/Link/__test__/__snapshots__/demo.test.ts.snap
Labels: 🐛 bug

#1137 fix(Typography): Short text folding problem in special scenes
  components/Typography/base.tsx
  components/Typography/useEllipsis.tsx
Labels: 🐛 bug

#1179 fix: Table hook deps
  components/Table/table.tsx
Labels: 🐛 bug

#1155 fix(Table): pagination onchange
  components/Table/table.tsx
Labels: 🐛 bug

#1176 fix(Modal): bug caused when Modal was hidden immediately after mounting
  components/Modal/modal.tsx
Labels: 🐛 bug

#1178 fix: Select onInputValueChange can't be triggered sometimes
  components/Select/__test__/index.test.tsx
  components/Select/select.tsx
Labels: 🐛 bug

#1184 Fix(Select): Fix flickering "no data" placeholder
  components/Select/select.tsx
Labels: 🐛 bug

#1212 feat: Slider supports RTL
  components/DatePicker/__test__/panel.test.tsx
  components/Slider/__demo__/direction.md
  components/Slider/__demo__/icon.md
  components/Slider/__demo__/input.md
  components/Slider/__demo__/reversed.md
  components/Slider/__demo__/set-range.md
  components/Slider/__demo__/status.md
  components/Slider/__demo__/step.md
  components/Slider/__demo__/tooltip.md
  components/Slider/__test__/__snapshots__/demo.test.ts.snap
  components/Slider/index.tsx
  components/Slider/interface.tsx
  components/Slider/style/index.less
  components/Slider/style/rtl.less
Labels: 💅 component style

#1217 fix(Table): paginationProps onChange callback can't be triggered
  components/Table/table.tsx
Labels: 🐛 bug

#1205 fix: Alert close button should have type='button'
  components/Alert/__test__/__snapshots__/demo.test.ts.snap
  components/Alert/index.tsx
Labels: 🐛 bug

#1215 fix: trigger can not work in react 18 strictmode
  components/Trigger/index.tsx
  components/Trigger/portal.tsx
Labels: 🐛 bug

#1213 feat: Resizebox supports RTL
  components/ResizeBox/index.tsx
  components/ResizeBox/resize-trigger.tsx
  components/ResizeBox/split-group.tsx
  components/ResizeBox/split.tsx
  components/ResizeBox/style/index.less
Labels: 💅 component style

#1207 fix(treeSelect): label displayed error
  components/Link/__test__/__snapshots__/demo.test.ts.snap
  components/Link/index.tsx
  components/Link/style/index.less
  components/Menu/style/index.less
  components/Select/style/index.less
  components/Select/style/token.less
  components/TreeSelect/__demo__/onSearch.md
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/__test__/index.test.tsx
  components/TreeSelect/hook/useStateValue.ts
Labels: 🐛 bug

#1211 enhance: Table expandProps.icon
  components/Select/select.tsx
  components/Table/__demo__/expandprops.md
  components/Table/tbody/tr.tsx
Labels: ⚡️ enhancement

#1210 fix: Carousel shouldn't slide to the first page when click the gap between indicators
  components/Carousel/indicator.tsx
  components/Carousel/style/index.less
  stories/Carousel.story.tsx
  stories/tsconfig.json
Labels: 🐛 bug

#1209 style: Table add rtl style
  components/Table/style/index.less
  components/Table/style/index.ts
  components/Table/summary/row.tsx
  components/Table/table.tsx
  components/Table/tbody/td.tsx
  components/Table/tbody/tr.tsx
  components/Table/thead/column.tsx
  components/Table/thead/index.tsx
  site/public/index.ejs
Labels: 💅 component style

#1188 fix: rangepicker change mode setpanelmode is undefined
  components/DatePicker/panels/date/index.tsx
Labels: 🐛 bug

#1219 fix(Image.Preview): fix the controlled logic for visible
  components/Image/__test__/preview.test.tsx
  components/Image/image-preview-group.tsx
  components/Image/image-preview.tsx
  components/Image/image.tsx
  components/Image/previewGroupContext.ts
Labels: 🐛 bug

#1222 fix: Mentions popup jitter
  components/Mentions/__test__/__snapshots__/demo.test.ts.snap
  components/Mentions/__test__/__snapshots__/index.test.tsx.snap
  components/Mentions/index.tsx
Labels: 🐛 bug
