Repository arco-design/arco-design, pull requests merged in 2022-10, with the labels that each got.

#1458 fix: Layout.Sider defaultCollapsed not work
  components/Layout/sider.tsx
Labels: 🐛 bug

#1457 fix: InputTag render children twice due to ReactTransitionGroup
  components/InputTag/input-tag.tsx
Labels: 🐛 bug

#1462 fix: the `shouldUpdate` property of the `Form.Item` component did not…
  components/Form/__test__/case.test.tsx
  components/Form/control.tsx
Labels: 🐛 bug

#1455 feat(Form): colon property supports ReactNode
  components/ConfigProvider/README.zh-CN.md
  components/Drawer/README.en-US.md
  components/Drawer/README.zh-CN.md
  components/Form/README.en-US.md
  components/Form/README.zh-CN.md
  components/Form/form-label.tsx
  components/Form/interface.tsx
  components/Table/README.zh-CN.md
Labels: ✨ feature

#1454 style(Tabs): fix the color of the add icon
  components/Tabs/style/index.less
Labels: 💅 component style

#1465 feat: add locale ms-MY
  components/locale/ms-MY.tsx
  site/docs/i18n.en-US.md
  site/docs/i18n.zh-CN.md
Labels: ✨ feature

#1463 fix: treeselect inputvalue can't change when it is controlled
  components/Cascader/cascader.tsx
  components/TreeSelect/tree-select.tsx
Labels: 🐛 bug

#1467 fix: The slider and have an out-of-order bug after the parent compo…
  components/Slider/__test__/index.test.tsx
  components/Slider/index.tsx
Labels: 🐛 bug

#1469 docs: fix DatePicker demo error in safari
  components/DatePicker/__demo__/timezone.md
  components/DatePicker/__demo__/utcOffset.md
Labels: 📖 documentation

#1459 feat: upload supports imagePreview & onDragOver & onDragLeave
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Upload/README.en-US.md
  components/Upload/README.zh-CN.md
  components/Upload/__demo__/preview.md
  components/Upload/__test__/__snapshots__/demo.test.ts.snap
  components/Upload/interface.tsx
  components/Upload/list/index.tsx
  components/Upload/list/pictureItem.tsx
  components/Upload/style/index.ts
  components/Upload/trigger-node.tsx
  components/Upload/upload.tsx
  components/Upload/uploader.tsx
Labels: ✨ feature

#1248 style(Tabs): Modify the problem that the header line is in the wrong position when the Tabs component is in type=line, tabPosition=bottom
  components/Tabs/style/index.less
Labels: 💅 component style

#1487 fix(Tabs): tab can't change when in right direction
  components/Tabs/__test__/index.test.tsx
  components/Tabs/tab-content.tsx
Labels: 🐛 bug

#1493 fix: forbid draging of disabled Transfer items
  components/Transfer/item.tsx
Labels: 🐛 bug

#1492 fix: Table foot height collapse when scroll.x is too small
  components/Table/style/index.less
Labels: 💅 component style

#1494 style: tabs extra flex-shrink
  components/Tabs/style/index.less
Labels: 💅 component style

#1484 fix: silder hooks usecallback
  components/Slider/hooks/useInterval.ts
  components/Slider/hooks/useLegalValue.ts
Labels: ⚡️ enhancement

#1515 style: border problem of text button in Button.Group
  components/Button/style/index.less
  stories/Button.story.tsx
Labels: 💅 component style

#1516 feat: InputNumber formatter add sencond paramter to notify user-typing status
  components/InputNumber/README.en-US.md
  components/InputNumber/README.zh-CN.md
  components/InputNumber/__test__/index.test.tsx
  components/InputNumber/index.tsx
  components/InputNumber/interface.ts
Labels: ⚡️ enhancement, ✨ feature

#1520 feat: Collase add property triggerRegion
  components/Collapse/README.en-US.md
  components/Collapse/README.zh-CN.md
  components/Collapse/__demo__/activeRegion.md
  components/Collapse/__test__/__snapshots__/demo.test.ts.snap
  components/Collapse/__test__/index.test.tsx
  components/Collapse/collapse.tsx
  components/Collapse/interface.ts
  components/Collapse/item.tsx
  components/Collapse/style/index.less
Labels: ✨ feature

#1517 enhance: Remove unnecessary searches in retainInputValueWhileSelect mode
  components/TreeSelect/__test__/index.test.tsx
  components/TreeSelect/tree-select.tsx
Labels: ⚡️ enhancement
