Repository arco-design/arco-design, pull requests merged in 2022-05, with the labels that each got.

#861 style: Statistic add token prefix and suffix margin
  components/Statistic/__test__/__snapshots__/demo.test.ts.snap
  components/Statistic/__test__/index.test.tsx
  components/Statistic/index.tsx
  components/Statistic/style/index.less
  components/Statistic/style/token.less
Labels: 💅 component style

#862 feat: ConfigProvider componentConfig add Timeline.Item
  components/ConfigProvider/interface.ts
  components/Timeline/__test__/__snapshots__/index.test.tsx.snap
  components/Timeline/__test__/index.test.tsx
  components/Timeline/item.tsx
Labels: ✨ feature

#860 fix: Table no header set scrollbar error
  components/Table/table.tsx
Labels: 🐛 bug

#864 feat: Form supports Form.useWatch & Form.useFormContext
  components/Form/__demo__/form-context.md
  components/Form/__demo__/useWatch.md
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/use.test.tsx
  components/Form/hooks/useContext.ts
  components/Form/hooks/useWatch.ts
  components/Form/index.tsx
  components/Form/interface.tsx
  components/Form/store.tsx
  components/Form/useForm.ts
Labels: ✨ feature

#857 fix(upload): Adjust the sequence of upload request parameters
  components/Upload/request.ts
Labels: 🐛 bug

#856 fix: Dropdown will prevent input element in dropdown menu get focused
  components/Dropdown/index.tsx
Labels: 🐛 bug

#854 fix: List's onReachBottom not triggered sometimes due to element.scro…
  components/List/index.tsx
Labels: 🐛 bug

#867 feat(Typography): ellipsisConfig.expand support controlled scene
  components/Typography/README.en-US.md
  components/Typography/README.zh-CN.md
  components/Typography/__test__/__snapshots__/demo.test.ts.snap
  components/Typography/__test__/index.test.tsx
  components/Typography/base.tsx
  components/Typography/interface.tsx
  components/Typography/operations.tsx
  stories/components/Typography.jsx
Labels: ✨ feature

#866 fix(Typography): The effect of `display:inline` such as `<code/>` on ellipsising
  components/Typography/base.tsx
  components/Typography/utils.tsx
Labels: 🐛 bug

#865 enhancement: InputNumber use non-scientific notation
  components/Dropdown/index.tsx
  components/InputNumber/__test__/index.test.tsx
  components/InputNumber/index.tsx
  components/InputNumber/utils.ts
  stories/components/InputNumber.jsx
Labels: ⚡️ enhancement

#817 feat: Rounded Tabs supports size
  components/Tabs/style/index.less
  components/Tabs/style/token.less
Labels: ✨ feature

#872 fix(table): fix group column has wrong border radius
  components/Table/style/index.less
Labels: 💅 component style

#869 fix(Form/useForm/store): `getFieldValue` should not change the store
  components/Form/__test__/useform.test.tsx
  components/Form/store.tsx
Labels: 🐛 bug

#892 fix(ResizeBox): Split.Group adaptive bug
  components/ResizeBox/__test__/group.test.tsx
  components/ResizeBox/split-group.tsx
Labels: 🐛 bug

#889 style: SubMenu icon does not show when Menu is collapsed
  .storybook/main.js
  components/Menu/indent.tsx
  components/Menu/style/index.less
Labels: 🐛 bug, 💅 component style

#890 fix: expanding operation display time
  components/Typography/__test__/__snapshots__/demo.test.ts.snap
  components/Typography/__test__/index.test.tsx
  components/Typography/base.tsx
  components/Typography/operations.tsx
  stories/components/Typography.jsx
Labels: 🐛 bug

#914 Feat datepicker panel render
  components/DatePicker/README.en-US.md
  components/DatePicker/README.zh-CN.md
  components/DatePicker/__test__/date.test.tsx
  components/DatePicker/interface.tsx
  components/DatePicker/picker.tsx
  stories/DatePicker.story.tsx
Labels: ✨ feature

#930 fix: form should clear warning status
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Form/README.en-US.md
  components/Form/README.zh-CN.md
  components/Form/__demo__/setFields.md
  components/Form/control.tsx
  components/_util/is.ts
Labels: 🐛 bug

#931 feat: Cascader supports inputValue and onInputValueChange
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Cascader/__demo__/custom_children.md
  components/Cascader/__demo__/search.md
  components/Cascader/cascader.tsx
  components/Cascader/interface.ts
Labels: ✨ feature

#929 fix: timeline label style in alternate mode
  components/Timeline/style/index.less
Labels: 🐛 bug, 💅 component style

#924 feat: add pt locale
  components/locale/pt-PT.tsx
Labels: ✨ feature

#913 feat(trigger): add a new prop "containerScrollToClose" supporting close popup when scrolling
  components/Trigger/README.en-US.md
  components/Trigger/README.zh-CN.md
  components/Trigger/index.tsx
  components/Trigger/interface.ts
Labels: ✨ feature

#921 fix: Dropdown.Menu's callback onMenuItemClick missing the third argument keyPath
  components/Dropdown/__test__/index.test.tsx
  components/Dropdown/index.tsx
Labels: 🐛 bug

#903 fix: Transfer custom list's select-all not work
  components/Transfer/__demo__/with-table.md
  components/Transfer/list.tsx
Labels: 🐛 bug

#923 style: sub-menu position of menu in pop mode
  components/Menu/style/index.less
Labels: 💅 component style

#922 feat: add language ru-RU
  components/locale/ru-RU.tsx
  stories/ConfigProvider.story.tsx
Labels: ✨ feature

#928 fix: radio ts
  components/Radio/interface.ts
  components/Radio/radio.tsx
Labels: ⚡️ enhancement

#932 feat: locale support ar-EG
  components/locale/ar-EG.tsx
  site/docs/i18n.zh-CN.md
Labels: ✨ feature

#925 feat: Upload supports imageRender & progressRender
  components/Upload/README.en-US.md
  components/Upload/README.zh-CN.md
  components/Upload/__test__/list.test.tsx
  components/Upload/interface.tsx
  components/Upload/list/pictureItem.tsx
  components/Upload/list/textItem.tsx
  components/Upload/list/uploadProgress.tsx
  components/Upload/style/index.less
  components/Upload/style/token.less
  components/Upload/uploader.tsx
Labels: ✨ feature

#934 fix(ResizeBox): Use percentage calculation to cover responsive scenarios
  components/ResizeBox/__test__/__snapshots__/demo.test.ts.snap
  components/ResizeBox/split-group.tsx
  stories/Resizebox.story.tsx
  stories/TODO/Resizebox.story.jsx
Labels: 🐛 bug

#937 feat(Layout): support resizebox props
  components/Layout/README.en-US.md
  components/Layout/README.zh-CN.md
  components/Layout/__demo__/resizeProps.md
  components/Layout/__test__/__snapshots__/demo.test.ts.snap
  components/Layout/__test__/index.test.tsx
  components/Layout/interface.ts
  components/Layout/sider.tsx
Labels: ✨ feature

#935 enhance(Typography): Reduce the number of first fold calculations
  components/Typography/base.tsx
Labels: ⚡️ enhancement
