Repository arco-design/arco-design, pull requests merged in 2022-08, with the labels that each got.

#1236 image native attribute onload does not trigger
  components/Image/__test__/index.test.tsx
  components/Image/image.tsx
Labels: 🐛 bug

#1233 fix: fix accept file util
  components/Upload/util.tsx
Labels: 🐛 bug

#1238 fix: DatePicker.WeekPicker locale format error
  components/DatePicker/panels/date/index.tsx
  components/DatePicker/picker-range.tsx
  components/DatePicker/picker.tsx
  components/DatePicker/util.ts
Labels: 🐛 bug

#1186 fix: iterativelyGetKeys should get all valid key
  components/Form/__test__/setfield.test.tsx
  components/Form/utils.tsx
Labels: 🐛 bug

#1267 feat: cascader supports showSearch.panelMode & showSearch.renderOption
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Cascader/__demo__/onSearch.md
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/__test__/search.test.tsx
  components/Cascader/cascader.tsx
  components/Cascader/interface.ts
  components/Cascader/panel/search-panel.tsx
  components/Cascader/util.tsx
  components/Slider/README.en-US.md
  components/Slider/README.zh-CN.md
Labels: ✨ feature

#1266 fix(Cascader): options render incorrect when virtualList is enabled
  components/Cascader/panel/search-panel.tsx
Labels: 🐛 bug

#1273 fix: DatePicker.RangePicker isOutofRange
  components/DatePicker/picker-range.tsx
Labels: 🐛 bug

#1270 fix: Table data item is arrry should render correctly
  components/Table/__test__/case.test.tsx
  components/Table/utils.tsx
Labels: 🐛 bug

#1276 enhancement: pagination , Collapse, tag keyboard events
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Collapse/item.tsx
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/__test__/__snapshots__/demo.test.ts.snap
  components/List/__test__/__snapshots__/demo.test.ts.snap
  components/Pagination/__test__/__snapshots__/demo.test.ts.snap
  components/Pagination/__test__/__snapshots__/index.test.tsx.snap
  components/Pagination/page-item.tsx
  components/Pagination/style/index.less
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/Table/__test__/__snapshots__/demo.test.ts.snap
  components/Tag/__test__/__snapshots__/demo.test.ts.snap
  components/Tag/index.tsx
  components/Tag/style/index.less
  components/Transfer/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/Trigger/__test__/__snapshots__/demo.test.ts.snap
  components/_util/hooks/useKeyboardEvent.ts
Labels: ⚡️ enhancement

#1268 fix: text ellipsis of Tag content
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Checkbox/__test__/__snapshots__/demo.test.ts.snap
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/input-tag.tsx
  components/InputTag/style/index.less
  components/PageHeader/__test__/__snapshots__/demo.test.ts.snap
  components/ResizeBox/__test__/__snapshots__/demo.test.ts.snap
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/Select/__test__/index.test.tsx
  components/Space/__test__/__snapshots__/demo.test.ts.snap
  components/Tabs/__test__/__snapshots__/demo.test.ts.snap
  components/Tag/__test__/__snapshots__/demo.test.ts.snap
  components/Tag/__test__/__snapshots__/index.test.tsx.snap
  components/Tag/index.tsx
  components/Tag/style/index.less
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/Trigger/__test__/__snapshots__/demo.test.ts.snap
Labels: 🐛 bug, 💅 component style

#1275 fix(Tabs): Fixed the bug that the width of the node of Tabs caused a…
  components/Tabs/tab-header/index.tsx
  stories/Tabs.story.tsx
Labels: 🐛 bug

#1274 feat(Image.Preview): Image.Preview support imageProps
  components/Image/README.en-US.md
  components/Image/README.zh-CN.md
  components/Image/__test__/preview.test.tsx
  components/Image/__test__/previewGroup.test.tsx
  components/Image/image-preview-group.tsx
  components/Image/image-preview.tsx
  components/Image/image.tsx
  components/Image/interface.ts
  components/Image/previewGroupContext.ts
  components/Tag/style/index.less
  stories/Image.story.tsx
Labels: ✨ feature

#1293 fix: DatePicker panelRender not work
  components/DatePicker/picker-range.tsx
  components/DatePicker/style/index.less
  stories/DatePicker.story.tsx
Labels: 🐛 bug

#1300 fix(useModal): the bug that the update function is undefined in the ModalInstance
  components/Modal/__test__/useModal.test.tsx
  components/Modal/useModal/index.tsx
Labels: 🐛 bug

#1303 enhance: export version
  components/index.tsx
  package.json
  scripts/dependencies.sh
  scripts/generate-version.js
Labels: ⚡️ enhancement

#1302 style: Select use the same ArrowIcon in both single/multiple mode
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Input/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/input-tag.tsx
  components/InputTag/style/index.less
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/Trigger/__test__/__snapshots__/demo.test.ts.snap
  components/_class/select-view.tsx
Labels: 💅 component style

#1312 enhancement: Menu hotkey operation
  components/Dropdown/style/index.less
  components/Menu/index.tsx
  components/Menu/style/index.less
  components/Menu/sub-menu/pop.tsx
Labels: ⚡️ enhancement

#1307 fix: Grid.Col won't display in larger screen size when it's set md=0
  components/Grid/style/col.less
  stories/Grid.story.tsx
Labels: 🐛 bug

#1304 enhancement: Optimize cascader edge case handling
  components/Cascader/__test__/case.test.tsx
  components/Cascader/util.tsx
Labels: ⚡️ enhancement

#1327 fix: Fixed the problem that the Select component was repeatedly introduced when the Cascader / TreeSelect style was introduced by on-demand loading
  .config/webpack.config.js
  components/Cascader/style/index.less
  components/InputTag/style/index.less
  components/InputTag/style/mixin.less
  components/Select/style/index.less
  components/Select/style/mixin.less
  components/TreeSelect/style/index.less
Labels: 🐛 bug

#1329 fix: the selected node was not scrolled to the viewport correctly whe…
  components/Cascader/panel/list.tsx
Labels: 🐛 bug

#1332 style: The collapsed button layout error in `LTR` scene
  components/Menu/style/index.less
Labels: 💅 component style

#1333 fix: pagination sizeOptions effect pageSize
  components/Pagination/__test__/index.test.tsx
  components/Pagination/pagination.tsx
Labels: 🐛 bug

#1336 fix: DatePicker half disabled
  components/DatePicker/__test__/range.test.tsx
  components/DatePicker/picker-range.tsx
Labels: 🐛 bug

#1328 enhancement: Select hotkey with a custom dropdown-menu
  components/Select/select.tsx
Labels: ⚡️ enhancement

#1334 fix: SSR error caused by global component DOM id
  components/BackTop/__test__/__snapshots__/demo.test.ts.snap
  components/Calendar/__test__/__snapshots__/demo.test.ts.snap
  components/Card/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/__test__/__snapshots__/index.test.tsx.snap
  components/Cascader/cascader.tsx
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Image/image.tsx
  components/Input/__test__/__snapshots__/demo.test.ts.snap
  components/Layout/__test__/__snapshots__/demo.test.ts.snap
  components/Menu/__test__/__snapshots__/demo.test.ts.snap
  components/Menu/index.tsx
  components/Menu/sub-menu/inline.tsx
  components/Menu/sub-menu/pop.tsx
  components/Pagination/__test__/__snapshots__/demo.test.ts.snap
  components/Progress/__test__/__snapshots__/demo.test.ts.snap
  components/Progress/circle-progress.tsx
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/Select/__test__/__snapshots__/index.test.tsx.snap
  components/Select/select.tsx
  components/Table/__test__/__snapshots__/demo.test.ts.snap
  components/Tabs/__test__/__snapshots__/demo.test.ts.snap
  components/Tabs/tabs.tsx
  components/TimePicker/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/tree-select.tsx
  components/Trigger/__test__/__snapshots__/demo.test.ts.snap
  components/_util/hooks/useId.ts
Labels: 🐛 bug

#1339 style: text ellipsis of InputTag's placeholder
  components/InputTag/style/index.less
Labels: 💅 component style

#1331 enhancement: horizontal Menu auto ellipsis might get wrapped in some specific menu-width
  components/Menu/__test__/index.test.tsx
  components/Menu/overflow-wrap.tsx
Labels: ⚡️ enhancement

#1341 fix: Table selectedRows, close #1294
  components/Table/__test__/case.test.tsx
  components/Table/hooks/useRowSelection.tsx
Labels: 🐛 bug
