Repository arco-design/arco-design, pull requests merged in 2022-02, with the labels that each got.

#519 fix: 修复upload组件触发onClick事件两次的问题
  components/Upload/uploader.tsx
Labels: bug

#513 feat: checkbox component and radio component support custom rendering…
  components/Checkbox/__demo__/custom_render.md
  components/Checkbox/__test__/__snapshots__/demo.test.ts.snap
  components/Checkbox/checkbox.tsx
  components/Checkbox/interface.ts
  components/Radio/__demo__/custom_render.md
  components/Radio/__test__/__snapshots__/demo.test.ts.snap
  components/Radio/radio.tsx
Labels: feature

#511 feat: Tree supports actionOnClick
  components/Tree/__test__/index.test.tsx
  components/Tree/context.tsx
  components/Tree/index.tsx
  components/Tree/interface.ts
  components/Tree/node.tsx
Labels: feature

#521 fix: Table filter onFilterDropdownVisibleChange
  components/Table/thead/column.tsx
Labels: bug

#501 refactor(popconfirm): expose new params of event for onCancel & onCon…
  components/Popconfirm/README.en-US.md
  components/Popconfirm/README.zh-CN.md
  components/Popconfirm/index.tsx
  components/Popconfirm/interface.ts
Labels: feature

#523 enhancement: cascader render logic
  components/Cascader/base/node.ts
  components/Cascader/base/store.ts
  components/Cascader/cascader.tsx
  components/Cascader/panel/list.tsx
  components/Cascader/panel/option.tsx
  components/Cascader/util.tsx
  stories/components/Cascader.jsx
Labels: enhancement

#488 fix(Timeline): add missing values in type definition
  components/Timeline/interface.ts
Labels: bug

#522 fix: Input will trigger onChange twice when input Chinese in Firefox
  components/Input/input-element.tsx
Labels: bug

#531 fix(Statistic): precison=0 not work
  components/Statistic/index.tsx
Labels: bug

#526 feat(TreeSelect): onChange supports extra params
  components/TreeSelect/README.en-US.md
  components/TreeSelect/README.zh-CN.md
  components/TreeSelect/__test__/index.test.tsx
  components/TreeSelect/hook/useStateValue.ts
  components/TreeSelect/interface.ts
  components/TreeSelect/tree-list.tsx
  components/TreeSelect/tree-select.tsx
Labels: feature

#533 fix: upload tip position when listtype=card
  components/Upload/trigger-node.tsx
  components/Upload/upload.tsx
Labels: component style

#530 enhancement(Trigger): Dom Element has been Forced Reflow when Trigger…
  components/Trigger/index.tsx
Labels: enhancement

#485 enhancement: allow user to visit RadioGroupContext
  components/Radio/group.tsx
  components/Radio/interface.ts
  components/Radio/radio.tsx
Labels: enhancement

#544 fix: cascader checkbox status error
  components/Cascader/cascader.tsx
Labels: bug

#539 fix(image): fix the problem that onload not be triggered when load form cache
  components/Image/image-preview.tsx
Labels: bug

#554 enhancement(Typography): Typography mirrorElement final performance
  components/InputTag/__demo__/draggable.md
  components/Typography/utils.tsx
  stories/components/Typography.jsx
Labels: enhancement

#568 fix(InputNumber) '.' not handled correctly #563
  components/InputNumber/index.tsx
Labels: bug

#579 fix(tooltip): does not show tooltip when content is false
  components/Tooltip/__test__/index.test.tsx
  components/Tooltip/index.tsx
Labels: bug

#584 fix: Input can not paste the same text after clear
  components/Input/input-element.tsx
Labels: bug

#577 fix(useForm): fix branch logic
  components/Form/useForm.ts
Labels: bug

#555 fix(Typography): the first parameter of listener function onStart of …
  components/Typography/operations.tsx
Labels: bug
