Repository arco-design/arco-design, pull requests merged in 2022-06, with the labels that each got.

#952 style: Tabs supports focus-visible style
  components/Card/__test__/__snapshots__/demo.test.ts.snap
  components/Tabs/__test__/__snapshots__/demo.test.ts.snap
  components/Tabs/style/index.less
  components/Tabs/style/token.less
  components/Tabs/tab-header/index.tsx
  components/Tabs/tab-header/tab-title.tsx
  components/Tabs/utils.tsx
Labels: 💅 component style

#949 style: Button add focus-visible style
  components/Button/style/index.less
  components/Button/style/token.less
  components/Upload/__test__/list.test.tsx
  stories/Button.story.tsx
Labels: 💅 component style

#980 fix: fix the problem of setting simple=false not working when using h…
  components/Modal/useModal/hookModal.tsx
  components/Modal/useModal/index.tsx
Labels: 🐛 bug

#955 fix: form useWatch value incorrect
  components/Form/__test__/use.test.tsx
  components/Form/hooks/useWatch.ts
  components/Form/store.tsx
  stories/Form.story.tsx
  stories/TODO/Form.story.jsx
  stories/TODO/Tooltip.story.jsx
  stories/Tooltip.story.tsx
Labels: 🐛 bug

#986 style: tooltip animation function
  components/style/animation/zoom.less
Labels: 💅 component style

#982 enhance: DatePicker dayStartOfWeek default is determined by locale
  components/DatePicker/README.en-US.md
  components/DatePicker/README.zh-CN.md
  components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
  components/DatePicker/__test__/date.test.tsx
  components/DatePicker/__test__/format.test.tsx
  components/DatePicker/__test__/panel.test.tsx
  components/DatePicker/__test__/range.hover.test.tsx
  components/DatePicker/__test__/range.test.tsx
  components/DatePicker/__test__/timezone.test.tsx
  components/DatePicker/__test__/week.test.tsx
  components/DatePicker/context.ts
  components/DatePicker/interface.tsx
  components/DatePicker/panels/body.tsx
  components/DatePicker/panels/date/index.tsx
  components/DatePicker/panels/range/index.tsx
  components/DatePicker/panels/week-list.tsx
  components/DatePicker/panels/week/index.tsx
  components/DatePicker/picker-range.tsx
  components/DatePicker/picker.tsx
  components/DatePicker/util.ts
  components/_util/dayjs.ts
Labels: ⚡️ enhancement

#972 feat: cascader supports virtual list & dropdownMenuClassname & dropd…
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Cascader/__test__/index.test.tsx
  components/Cascader/__test__/search.test.tsx
  components/Cascader/cascader.tsx
  components/Cascader/interface.ts
  components/Cascader/panel/list.tsx
  components/Cascader/panel/search-panel.tsx
  components/Cascader/style/index.less
  components/Cascader/style/token.less
  components/_class/VirtualList/index.tsx
  stories/Cascader.story.tsx
Labels: ✨ feature

#983 fix: controlled cascader can not select options when checkedStrategy=…
  components/Cascader/__test__/index.test.tsx
  components/Cascader/cascader.tsx
Labels: 🐛 bug

#953 fix: labelInValue not work in Select with a initial LabeledValue
  components/Select/__test__/index.test.tsx
  components/Select/select.tsx
Labels: 🐛 bug

#988 fix: textarea maxLength may not work while inputing Chinese
  components/Input/__test__/index.test.tsx
  components/Input/input-element.tsx
  components/Input/input.tsx
  components/Input/interface.tsx
  components/Input/textarea.tsx
  components/Input/useComposition.ts
  components/InputTag/input-tag.tsx
  components/Mentions/__test__/index.test.tsx
  components/Typography/__test__/index.test.tsx
  components/_class/select-view.tsx
  stories/Typography.story.tsx
Labels: 🐛 bug

#990 fix: Table should not change origin data
  components/Table/hooks/useRowSelection.tsx
  components/Table/table.tsx
  components/Table/utils.tsx
  stories/Table.story.tsx
Labels: 🐛 bug

#1011 enhancenment: mark Select options that are created/creating by user self via DOM attribute
  components/Select/interface.tsx
  components/Select/option.tsx
  components/Select/select.tsx
Labels: ⚡️ enhancement

#1009 enhance: DatePicker hover style
  components/DatePicker/__test__/range.hover.test.tsx
  components/DatePicker/hooks/useCellClassName.ts
  components/DatePicker/style/index.less
Labels: 💅 component style

#981 refactor(Typography): Code refactoring of the ellipsis mode logic. Using css by default
  components/Typography/__test__/__snapshots__/demo.test.ts.snap
  components/Typography/__test__/index.test.tsx
  components/Typography/base.tsx
  components/Typography/style/index.less
  components/Typography/useCssEllipsis.tsx
  components/Typography/useEllipsis.tsx
  components/Typography/utils.tsx
Labels: ⚡️ enhancement

#1029 Sfj/fix tree select/cascader dragtosort
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Cascader/__demo__/draggable.md
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/cascader.tsx
  components/Cascader/interface.ts
  components/TreeSelect/__demo__/draggable.md
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/tree-select.tsx
Labels: 🐛 bug

#1041 fix: DatePicker first select range
  components/DatePicker/picker-range.tsx
Labels: 🐛 bug

#1040 style: make sure vertical-align of Pagination item-jumper's icon is center
  components/Pagination/style/index.less
Labels: 💅 component style

#1043 style: Dropdown should hide itself when it's empty
  components/Dropdown/index.tsx
Labels: 💅 component style

#1039 refactor: The default value of cssEllipsis becomes false, unit test add
  components/Typography/README.en-US.md
  components/Typography/README.zh-CN.md
  components/Typography/__test__/css-ellipsis.test.tsx
  components/Typography/__test__/index.test.tsx
  components/Typography/__test__/js-ellipsis.test.tsx
  components/Typography/base.tsx
  components/Typography/interface.tsx
  components/Typography/useCssEllipsis.tsx
Labels: ⚡️ enhancement

#1044 feat(Statistic): support renderFormat
  components/Statistic/README.en-US.md
  components/Statistic/README.zh-CN.md
  components/Statistic/__demo__/countdown.md
  components/Statistic/__test__/__snapshots__/demo.test.ts.snap
  components/Statistic/__test__/countdown.test.tsx
  components/Statistic/__test__/index.test.tsx
  components/Statistic/countdown.tsx
  components/Statistic/index.tsx
  components/Statistic/interface.ts
Labels: ✨ feature

#1045 enhancement: Transfer header unit-text on simple mode
  components/Transfer/__test__/__snapshots__/demo.test.ts.snap
  components/Transfer/index.tsx
  components/Transfer/interface.tsx
  components/Transfer/list.tsx
  components/Transfer/style/index.less
Labels: ⚡️ enhancement

#1038 enhancement: Menu support operate by Tab key
  components/Layout/__test__/__snapshots__/demo.test.ts.snap
  components/Menu/__test__/__snapshots__/demo.test.ts.snap
  components/Menu/__test__/__snapshots__/index.test.tsx.snap
  components/Menu/__test__/index.test.tsx
  components/Menu/context.ts
  components/Menu/hotkey.ts
  components/Menu/index.tsx
  components/Menu/item.tsx
  components/Menu/style/index.less
  components/Menu/sub-menu/inline.tsx
  components/Menu/sub-menu/pop.tsx
  components/Tabs/tab-header/tab-title.tsx
  stories/Affix.story.tsx
Labels: ⚡️ enhancement

#1042 fix: avoid InputNumber being interfered with by Input's global config
  components/Input/interface.tsx
  components/InputNumber/index.tsx
  components/Pagination/page-jumper.tsx
  components/_util/hooks/useMergeProps.ts
Labels: 🐛 bug

#1047 fix: Table output data and record should not contains internal data
  components/Table/hooks/useExpand.tsx
  components/Table/hooks/useRowSelection.tsx
  components/Table/table.tsx
  components/Table/tbody/index.tsx
  components/Table/tbody/td.tsx
  components/Table/tbody/tr.tsx
  components/Table/tfoot/index.tsx
  components/Table/utils.tsx
  stories/Table.story.tsx
Labels: 🐛 bug
