Repository arco-design/arco-design, pull requests merged in 2022-01, with the labels that each got.

#402 style: divider text wrap line
  components/Divider/style/index.less
Labels: component style

#399 fix: Menu in Dropdown can not set width by style.width
  components/Menu/index.tsx
Labels: bug

#401 feat: Transfer supports passing InputProps to showSearch
  components/Transfer/README.en-US.md
  components/Transfer/README.zh-CN.md
  components/Transfer/index.tsx
  components/Transfer/interface.tsx
  components/Transfer/list.tsx
Labels: feature

#407 fix: Input composition error
  components/Input/__test__/index.test.tsx
  components/Input/input-element.tsx
Labels: bug

#410 fix: image preview configContext
  components/Image/image-preview.tsx
  stories/components/Image.jsx
Labels: bug

#409 fix: Carousel's first page switch animation is abnormal when currentIndex is set to non-zero
  components/Carousel/index.tsx
Labels: bug

#400 feat(Form): supports validateTrigger props
  components/Form/README.en-US.md
  components/Form/README.zh-CN.md
  components/Form/__template__/index.en-US.md
  components/Form/__template__/index.zh-CN.md
  components/Form/__test__/validate.test.tsx
  components/Form/control.tsx
  components/Form/form-item.tsx
  components/Form/form.tsx
  components/Form/interface.tsx
Labels: feature

#411 style: Button mini size vertical-align
  components/Button/style/token.less
Labels: component style

#415 doc: update document for Material Market
  site/docs/material/advanced.team-site.en-US.md
  site/docs/material/advanced.team-site.zh-CN.md
Labels: documentation

#416 feat: The limit parameter of the `Upload` component supports specifying that the upload node is disabled after the limit number is exceede
  components/Upload/README.en-US.md
  components/Upload/README.zh-CN.md
  components/Upload/__test__/apis.test.tsx
  components/Upload/interface.tsx
  components/Upload/upload.tsx
  components/Upload/uploader.tsx
Labels: feature

#440 fix: tabs scroll position
  components/Tabs/tab-header/index.tsx
  components/Tabs/utils.tsx
  stories/components/Tab.jsx
Labels: bug

#446 fix: anchor scroll position error when scrollContainer is not window
  components/Anchor/anchor.tsx
Labels: bug

#419 make children of Select.Option optional
  components/Select/interface.tsx
  components/Select/option.tsx
Labels: enhancement

#444 fix: form scrollToFirst not work
  components/Form/__test__/form.test.tsx
  components/Form/control.tsx
  components/Form/form-label.tsx
  components/Form/form.tsx
  components/Form/utils.tsx
Labels: bug

#445 fix: image preview index
  components/Image/image-preview-group.tsx
  components/Image/image-preview.tsx
  components/Image/image.tsx
  components/Image/previewGroupContext.ts
  stories/components/Image.jsx
Labels: bug

#439 enhancement: turn off autocomplete for Select & InputTag
  components/BackTop/__test__/__snapshots__/demo.test.ts.snap
  components/Calendar/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/__test__/__snapshots__/index.test.tsx.snap
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Input/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/__test__/__snapshots__/index.test.tsx.snap
  components/InputTag/input-tag.tsx
  components/Pagination/__test__/__snapshots__/demo.test.ts.snap
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/Select/__test__/__snapshots__/index.test.tsx.snap
  components/Table/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/Trigger/__test__/__snapshots__/demo.test.ts.snap
  components/_class/select-view.tsx
Labels: enhancement

#437 enhancement: Dropdown add className arco-dropdown for popup element
  components/Dropdown/index.tsx
Labels: enhancement

#441 fix: The ellipsis calculation of typography in the zoom scene is wrong
  components/Typography/__test__/index.test.tsx
  components/Typography/utils.tsx
  stories/components/Typography.jsx
Labels: bug

#448 fix: Select renderFormat should return parameter value with valid lab…
  components/Select/__test__/index.test.tsx
  components/Select/select.tsx
Labels: enhancement

#450 enhancement: Select.Option without children
  components/Select/option.tsx
  components/Select/select.tsx
Labels: enhancement

#460 fix: correct the type of SkeletonTextProps
  components/Skeleton/interface.tsx
Labels: bug

#457 fix(Upload): expand the clickable area of the remove button
  components/Upload/list/textItem.tsx
Labels: bug

#455 fix: the in property of csstransition should receive a boolean value
  components/Badge/__demo__/dot.md
  components/Badge/index.tsx
Labels: bug

#471 fix(button): fix incorrectly style when button content is empty
  components/Button/style/index.less
Labels: bug

#472 enhance: Table virtualized optimization
  components/Table/__demo__/virtualized.md
  components/Table/__test__/__snapshots__/demo.test.ts.snap
  components/Table/hooks/useRowSelection.tsx
  components/Table/thead/index.tsx
Labels: enhancement

#480 enhancement: Grid.Col support span 0
  components/Grid/col.tsx
  components/Grid/style/col.less
Labels: enhancement

#482 fix: InputTag prevent enter key to submit form
  components/InputTag/input-tag.tsx
Labels: enhancement

#466 fix(select): fix allowCreate and tokenSeparators property is conflict
  components/Select/__test__/index.test.tsx
  components/Select/select.tsx
Labels: bug
