Repository arco-design/arco-design, pull requests merged in 2023-04, with the labels that each got.

#1899 ts: modify input.textarea ref ts
  components/Input/textarea.tsx
Labels: ⚡️ enhancement

#1898 fix: trigered an unexpected onChange event when adding item to Form…
  components/Form/control.tsx
  components/Form/store.tsx
Labels: 🐛 bug

#1902 fix: only close top level drawer when esc
  components/Drawer/index.tsx
  components/Modal/modal.tsx
Labels: 🐛 bug

#1894 fix(Select): Select will be focused after clicking the close icon of value-tag
  components/InputTag/input-tag.tsx
Labels: 🐛 bug

#1919 fix: RangePicker pickerValue update when mode change
  components/DatePicker/picker-range.tsx
Labels: 🐛 bug

#1900 style: statistic decimal style
  components/Statistic/README.en-US.md
  components/Statistic/README.zh-CN.md
  components/Statistic/index.tsx
  components/Statistic/interface.ts
Labels: ✨ feature

#1897 ts: modify grid-item interfaces
  components/Grid/grid-item.tsx
  components/Grid/grid.tsx
  components/Grid/interface.ts
  components/Trigger/index.tsx
  stories/Grid.story.tsx
Labels: ✨ feature

#1913 fix: fix table indent
  components/Table/style/index.less
  stories/Table.story.tsx
Labels: 🐛 bug

#1920 fix: DatePicker.RangePicker onPickerValueChange when reset
  components/DatePicker/picker-range.tsx
Labels: 🐛 bug

#1910 Feat/multiple sorter
  components/Table/README.en-US.md
  components/Table/README.zh-CN.md
  components/Table/__demo__/drag-handle.md
  components/Table/__demo__/drag.md
  components/Table/__demo__/fixed-column.md
  components/Table/__demo__/group-columns.md
  components/Table/__demo__/header-sticky.md
  components/Table/__demo__/multiple-sorter.md
  components/Table/__demo__/operations.md
  components/Table/__demo__/pagination.md
  components/Table/__demo__/render.md
  components/Table/__demo__/resizable.md
  components/Table/__demo__/rowspan.md
  components/Table/__demo__/style.md
  components/Table/__demo__/summary.md
  components/Table/__demo__/table-edit.md
  components/Table/__demo__/virtualized.md
  components/Table/__test__/__snapshots__/demo.test.ts.snap
  components/Table/__test__/common/columns.tsx
  components/Table/__test__/common/data.ts
  components/Table/__test__/multiple-sorter.test.tsx
  components/Table/hooks/useColumns.tsx
  components/Table/hooks/useSorter.tsx
  components/Table/interface.tsx
  components/Table/table.tsx
  components/Table/tbody/td.tsx
  components/Table/tbody/tr.tsx
  components/Table/thead/index.tsx
  components/Table/utils.tsx
  stories/Table.story.tsx
Labels: ✨ feature

#1917 feat(Tabs): icons support scroll config
  components/Tabs/README.en-US.md
  components/Tabs/README.zh-CN.md
  components/Tabs/__test__/__snapshots__/tabs-header.test.tsx.snap
  components/Tabs/__test__/tabs-header.test.tsx
  components/Tabs/hook/useDomSize.ts
  components/Tabs/interface.ts
  components/Tabs/tab-header/dropdown-icon.tsx
  components/Tabs/tab-header/index.tsx
  components/Tabs/tab-header/tab-nav-icon.tsx
Labels: ✨ feature

#1918 feat: InputTag support prefix/addbefore/addafter
  components/InputTag/README.en-US.md
  components/InputTag/README.zh-CN.md
  components/InputTag/__demo__/prefix.md
  components/InputTag/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/input-tag.tsx
  components/InputTag/interface.ts
  components/InputTag/style/index.less
  components/InputTag/style/token.less
  components/Select/style/mixin.less
  components/_class/select-view.tsx
Labels: ✨ feature

#1922 fix: grid overflow property
  components/Grid/context.ts
  components/Grid/grid-item.tsx
  components/Grid/grid.tsx
Labels: 🐛 bug

#1915 fix(Select): triggerProps.trigger=focus not works
  components/_class/select-view.tsx
Labels: 🐛 bug

#1934 chore: update browserslistrc
  .browserslistrc
  README.md
  icon/index.js
  yarn.lock
Labels: 🐛 bug

#1937 fix: Pagination hiden when no data
  components/Table/table.tsx
Labels: 🐛 bug

#1935 fix: Select width changes slowly after selected value tags are cleared
  components/Input/input-element.tsx
  components/InputTag/style/index.less
Labels: 🐛 bug

#1938 fix(tree): node can not be checked when show child
  components/Tree/__test__/case.test.tsx
  components/Tree/index.tsx
  components/Tree/util.tsx
  stories/TODO/Tree.story.jsx
  stories/TreeSelect.story.tsx
Labels: 🐛 bug
