Repository arco-design/arco-design, pull requests merged in 2023-06, with the labels that each got.

#2005 fix: Table when no data, but pagination.total > 0, should show pagina…
  components/Table/__test__/pagination.test.tsx
  components/Table/table.tsx
Labels: 🐛 bug

#2006 feat: drawer supports closeIcon
  components/Drawer/README.en-US.md
  components/Drawer/README.zh-CN.md
  components/Drawer/__test__/index.test.tsx
  components/Drawer/index.tsx
  components/Drawer/interface.ts
  components/Table/README.en-US.md
  components/Table/README.zh-CN.md
Labels: ✨ feature

#2004 style: pagination add suffix & update text color
  components/Form/interface.tsx
  components/Pagination/__test__/__snapshots__/demo.test.ts.snap
  components/Pagination/page-jumper.tsx
  components/Pagination/style/index.less
  components/Pagination/style/token.less
Labels: ui

#2008 feat: useNotification supports getContainer
  components/Notification/__demo__/useNotification.md
  components/Notification/__test__/useNotification.test.tsx
  components/Notification/index.tsx
  components/Notification/useNotification.tsx
Labels: ✨ feature

#2023 fix: timepicker warning in dev
  components/TimePicker/time-column.tsx
Labels: 🐛 bug

#2024 fix: cascader can not be delete by backspace
  components/Cascader/__test__/case.test.tsx
  components/Cascader/__test__/index.test.tsx
  components/Cascader/panel/list.tsx
Labels: 🐛 bug

#2035 enhance(Transfer): onChange callback value is inconsistent with the order of target list items
  components/Transfer/__test__/index.test.tsx
  components/Transfer/index.tsx
Labels: ⚡️ enhancement

#2036 fix: DatePicker showTime.defaultValue not correct when set timezone
  components/DatePicker/picker-range.tsx
  components/DatePicker/picker.tsx
Labels: 🐛 bug

#2037 fix(Statistics): prefix is not rendered if value is not a number
  components/Statistic/index.tsx
Labels: 🐛 bug

#2060 feat(Message): supports closeIcon
  components/Message/README.en-US.md
  components/Message/README.zh-CN.md
  components/Message/__test__/index.test.tsx
  components/Message/interface.ts
  components/_class/notice.tsx
Labels: ✨ feature

#2064 fix(Select): select-view is affected by InputTag properties inherit from ConfigProvider.componentConfig.InputTag
  components/_class/select-view.tsx
Labels: 🐛 bug

#2063 fix(Carousel): slide not working properly if trigger is [hover]
  components/Carousel/indicator.tsx
Labels: 🐛 bug

#2058 type(Descriptions): DescriptionsProps.column missing [xxxl] option
  components/Descriptions/interface.ts
Labels: 📖 documentation

#2056 fix: VirtualList outerStyle not worked when list is not virtual
  components/_class/VirtualList/index.tsx
Labels: 🐛 bug

#2065 feat: Input supports valueNormalize
  components/Input/README.en-US.md
  components/Input/README.zh-CN.md
  components/Input/__demo__/basic.md
  components/Input/__demo__/normalize.md
  components/Input/__test__/__snapshots__/demo.test.ts.snap
  components/Input/__test__/index.test.tsx
  components/Input/input-element.tsx
  components/Input/interface.tsx
  components/Input/useComposition.ts
  components/Modal/README.en-US.md
  components/Modal/README.zh-CN.md
Labels: ✨ feature
