Repository arco-design/arco-design, pull requests merged in 2023-12, with the labels that each got.

#2397 perf: optimize form getKeys func
  components/Form/utils.tsx
Labels: ⚡️ enhancement

#2393 fix(form): fix undefined problem
  components/Form/store.tsx
Labels: 🐛 bug

#2412 fix(drawer): fix autoFocus problem
  components/Drawer/index.tsx
Labels: 🐛 bug

#2407 fix: close Message
  components/_class/notification.tsx
Labels: 🐛 bug

#2426 feat(Menu): new property onEllipsisChange for horizontal-menu ellipsis status change
  components/Menu/README.en-US.md
  components/Menu/README.zh-CN.md
  components/Menu/index.tsx
  components/Menu/interface.tsx
  components/Menu/overflow-wrap.tsx
Labels: ✨ feature

#2437 fix: fix watermark text size when rotate
  components/_hooks/useWatermark/index.ts
Labels: 🐛 bug

#2447 fix(Select): allowCreate.formatter not work for Select with single mode
  components/Select/__test__/index.test.tsx
  components/Select/select.tsx
Labels: 🐛 bug

#2454 fix(scripts): fix icon init problem
  icon/build/getSvgData.js
Labels: 🐛 bug

#2455 fix(select): 最后一个选项被清除时,高度会闪现2行的高度直到标签完全消失 (#2451)
  components/InputTag/input-tag.tsx
Labels: ⚡️ enhancement
