Repository arco-design/arco-design, pull requests merged in 2023-10, with the labels that each got.

#2277 enhance: divider line style inherit
  components/Divider/style/index.less
Labels: ⚡️ enhancement

#2259 feat(Select): allowCreate support formatter fn to customize user-created option label
  components/Cascader/interface.ts
  components/Select/README.en-US.md
  components/Select/README.zh-CN.md
  components/Select/__demo__/allow-create.md
  components/Select/__test__/index.test.tsx
  components/Select/interface.tsx
  components/Select/select.tsx
  components/Select/utils.tsx
  components/TreeSelect/interface.ts
  components/_class/select-view.tsx
Labels: ✨ feature

#2274 feat: input and select all support autoWidth
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Input/README.en-US.md
  components/Input/README.zh-CN.md
  components/Input/__demo__/autoWidth.md
  components/Input/__test__/__snapshots__/demo.test.ts.snap
  components/Input/input-element.tsx
  components/Input/input.tsx
  components/Input/interface.tsx
  components/Input/style/index.less
  components/InputTag/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/__test__/__snapshots__/index.test.tsx.snap
  components/InputTag/input-tag.tsx
  components/InputTag/style/index.less
  components/Select/README.en-US.md
  components/Select/README.zh-CN.md
  components/Select/__demo__/autoWidth.md
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/TimePicker/__test__/__snapshots__/demo.test.ts.snap
  components/Tree/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/README.en-US.md
  components/TreeSelect/README.zh-CN.md
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/Trigger/__test__/__snapshots__/demo.test.ts.snap
  components/_class/select-view.tsx
  components/_util/fillNBSP.ts
Labels: ✨ feature

#2278 feat: tabs support inkbarsize
  components/Tabs/interface.ts
  components/Tabs/style/index.less
  components/Tabs/style/vertical.less
  components/Tabs/tab-header/index.tsx
  components/Tabs/tab-header/tab-ink.tsx
Labels: ✨ feature

#2255 修复因按钮事件抖动引起的异常
  components/InputNumber/index.tsx
Labels: 🐛 bug

#2287 enhance(pagination): enhance jumper blur
  components/Pagination/page-jumper.tsx
Labels: ⚡️ enhancement

#2302 fix: DatePicker.RangePicker shortcuts={[]} unexpected display 0
  components/DatePicker/picker-range.tsx
  components/DatePicker/picker.tsx
Labels: 🐛 bug

#2301 fix(Spin): render child when it is 0/NaN
  components/Spin/__test__/index.test.tsx
  components/Spin/index.tsx
  components/_util/is.ts
Labels: 🐛 bug

#2294 fix: button-group radius style.
  components/Button/style/index.less
Labels: 💅 component style

#2229 perf: remove temp objects at every render, store as const vars.
  components/Cascader/cascader.tsx
  components/DatePicker/picker-range.tsx
  components/DatePicker/picker.tsx
  components/Dropdown/index.tsx
  components/Select/select.tsx
  components/Slider/button.tsx
  components/Table/thead/column.tsx
  components/TimePicker/picker.tsx
  components/Tooltip/index.tsx
  components/TreeSelect/tree-select.tsx
Labels: ⚡️ enhancement

#2312 fix: form ui
  components/Form/__demo__/async-validate.md
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Form/control.tsx
  components/Form/form-item.tsx
  components/Form/hooks/useContext.ts
  components/Form/interface.tsx
  components/Form/store.tsx
  components/Form/style/status.less
Labels: 🐛 bug

#2297 feat: Upload support method prop
  components/Upload/README.en-US.md
  components/Upload/README.zh-CN.md
  components/Upload/__test__/index.test.tsx
  components/Upload/interface.tsx
  components/Upload/request.ts
  components/Upload/upload.tsx
  components/Upload/uploader.tsx
Labels: ✨ feature

#2324 feat: Trigger clickoutside supports capture
  components/Trigger/README.en-US.md
  components/Trigger/README.zh-CN.md
  components/Trigger/index.tsx
  components/Trigger/interface.ts
  site/docs_spec/style-guideline.en-US.md
  site/docs_spec/style-guideline.zh-CN.md
Labels: ✨ feature

#2323 fix: DatePicker.RangePicker stop default behavior
  components/_class/picker/input-range.tsx
Labels: 🐛 bug

#2320 enhance(image): add preview-group key event
  components/Image/image-preview.tsx
  stories/Image.story.tsx
Labels: ⚡️ enhancement

#2315 style(Input): vertical jitter in Safari when clear text content of input-box
  components/Input/style/index.less
Labels: 💅 component style

#2316 fix(List): error caused by getting scrollTop from [null]
  components/List/index.tsx
Labels: 🐛 bug

#2325 enhancement: Datepicker panel order
  components/DatePicker/panels/date/index.tsx
  components/DatePicker/panels/header.tsx
  components/DatePicker/panels/month/index.tsx
  components/locale/ar-EG.tsx
  components/locale/de-DE.tsx
  components/locale/en-US.tsx
  components/locale/es-ES.tsx
  components/locale/fr-FR.tsx
  components/locale/id-ID.tsx
  components/locale/interface.tsx
  components/locale/it-IT.tsx
  components/locale/ja-JP.tsx
  components/locale/ko-KR.tsx
  components/locale/ms-MY.tsx
  components/locale/pt-PT.tsx
  components/locale/ru-RU.tsx
  components/locale/th-TH.tsx
  components/locale/tr-TR.tsx
  components/locale/vi-VN.tsx
  components/locale/zh-CN.tsx
  components/locale/zh-HK.tsx
  components/locale/zh-TW.tsx
Labels: ⚡️ enhancement

#2308 feat: add Input.VerificationCode
  components/ConfigProvider/interface.ts
  components/Form/README.en-US.md
  components/Form/README.zh-CN.md
  components/Form/interface.tsx
  components/Select/README.en-US.md
  components/Select/README.zh-CN.md
  components/Tabs/README.en-US.md
  components/Tabs/README.zh-CN.md
  components/VerificationCode/README.en-US.md
  components/VerificationCode/README.zh-CN.md
  components/VerificationCode/__changelog__/index.en-US.md
  components/VerificationCode/__changelog__/index.zh-CN.md
  components/VerificationCode/__demo__/basic.md
  components/VerificationCode/__demo__/mask.md
  components/VerificationCode/__demo__/seperator.md
  components/VerificationCode/__demo__/status.md
  components/VerificationCode/__demo__/validate.md
  components/VerificationCode/__demo__/with-form.md
  components/VerificationCode/__template__/index.en-US.md
  components/VerificationCode/__template__/index.zh-CN.md
  components/VerificationCode/__test__/__snapshots__/demo.test.ts.snap
  components/VerificationCode/__test__/__snapshots__/index.test.tsx.snap
  components/VerificationCode/__test__/demo.test.ts
  components/VerificationCode/__test__/index.test.tsx
  components/VerificationCode/hooks/useVerificationCode.ts
  components/VerificationCode/index.tsx
  components/VerificationCode/interface.ts
  components/VerificationCode/style/index.less
  components/VerificationCode/style/index.ts
  components/VerificationCode/style/token.less
  components/VerificationCode/verification-code.tsx
  components/index.tsx
  site/src/locale/en.js
  site/src/locale/zh.js
  site/src/routes.js
Labels: ✨ feature

#2327 feat: DatePicker.RangePicker format can use string[]
  components/DatePicker/__test__/format.test.tsx
  components/DatePicker/interface.tsx
  components/DatePicker/panels/range/index.tsx
  components/DatePicker/picker-range.tsx
  components/DatePicker/util.ts
  components/_class/picker/input-range.tsx
  components/_util/dayjs.ts
Labels: ✨ feature
