Repository arco-design/arco-design, pull requests merged in 2023-09, with the labels that each got.

#2201 style(Cascader): panel item arrow style in rtl direction
  components/Cascader/cascader.tsx
  components/Menu/style/index.less
Labels: 🐛 bug, 💅 component style

#2198 style(Transfer): list item overflow
  components/Transfer/style/index.less
Labels: 💅 component style

#2204 fix: form item disbaled
  components/Form/__test__/case.test.tsx
  components/Form/control.tsx
  components/Form/form-item.tsx
  tests/screenshots.js
Labels: 🐛 bug

#2190 fix(Select): dropdown-down won't show after clicking if use renderFormat with showSearch
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/__test__/__snapshots__/index.test.tsx.snap
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/Input/__test__/__snapshots__/demo.test.ts.snap
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/Select/__test__/__snapshots__/index.test.tsx.snap
  components/Select/style/mixin.less
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/_class/select-view.tsx
Labels: 🐛 bug

#2216 fix(VirtualList): error caused by get clientHeight from null
  components/_class/VirtualList/index.tsx
Labels: 🐛 bug

#2217 fix(Select): active option should change after input value changed
  components/Select/__test__/index.test.tsx
  components/Select/select.tsx
Labels: 🐛 bug

#2222 fix: drawer esc not work
  components/Drawer/__test__/index.test.tsx
  components/Drawer/index.tsx
Labels: 🐛 bug

#2219 fix: tree-select should rerender Text when treeData change
  components/TreeSelect/__test__/index.test.tsx
  components/TreeSelect/tree-select.tsx
Labels: 🐛 bug

#2224 feat(Image): support specify extra node in ImagePreview container
  components/Image/README.en-US.md
  components/Image/README.zh-CN.md
  components/Image/image-preview.tsx
  components/Image/interface.ts
Labels: ✨ feature

#2223 fix(Image): image shows error placeholder during first render
  components/Image/__test__/__snapshots__/demo.test.ts.snap
  components/Image/image.tsx
  components/_util/hooks/useInView.ts
Labels: 🐛 bug

#2226 feat: Table ref add scrollIntoView
  components/Table/__demo__/virtualized.md
  components/Table/__test__/__snapshots__/demo.test.ts.snap
  components/Table/interface.tsx
  components/Table/table.tsx
  components/Table/tbody/index.tsx
  components/index.tsx
  stories/Table.story.tsx
Labels: ✨ feature

#2232 fix: drawer esc not work
  components/Drawer/index.tsx
Labels: 🐛 bug

#2233 fix(Select): dropdown-box need click twice to show in Firefox
  components/Select/style/mixin.less
Labels: 🐛 bug

#2235 enhance: Modal,Message,Notification export hook return type
  components/Message/index.tsx
  components/Message/interface.ts
  components/Message/useMessage.tsx
  components/Modal/interface.ts
  components/Modal/useModal/index.tsx
  components/Notification/index.tsx
  components/Notification/interface.ts
  components/Notification/useNotification.tsx
  components/index.tsx
Labels: ⚡️ enhancement

#2236 enhance: tree-select in large data
  components/Tree/context.tsx
  components/Tree/index.tsx
  components/Tree/node-list.tsx
  components/_class/VirtualList/index.tsx
  stories/TreeSelect.story.tsx
Labels: ⚡️ enhancement

#2250 fix(Message): Message.config cannot set rtl from true to false
  components/Drawer/__demo__/container.md
  components/Message/index.tsx
  components/Notification/index.tsx
Labels: 🐛 bug

#2239 fix(Input): 修复Search组件受控状态异常问题
  components/Input/search.tsx
Labels: 🐛 bug
