Repository arco-design/arco-design, pull requests merged in 2023-08, with the labels that each got.

#2025 fix: time-picker disabled error
  components/TimePicker/time-picker.tsx
Labels: 🐛 bug

#2120 fix(InputNumber): avoid string replace error due to undefined
  components/InputNumber/index.tsx
Labels: 🐛 bug

#2122 fix(Select): container lose width after focused if Select has a default value
  components/_class/select-view.tsx
Labels: 🐛 bug

#2138 fix(Menu): avoid tranforming single child to array while processing menu children
  components/Menu/__test__/index.test.tsx
  components/Menu/util.ts
Labels: 🐛 bug

#2141 enhancement: get Content Size by offsetWidth
  components/Trigger/getPopupStyle.ts
Labels: ⚡️ enhancement

#2156 fix(Select): dropdown-menu won't show if click the disabled input-element of Select
  components/Select/style/mixin.less
Labels: 🐛 bug

#2062 feat(Cascader): support icons
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Cascader/__test__/index.test.tsx
  components/Cascader/cascader.tsx
  components/Cascader/interface.ts
  components/Cascader/panel/list.tsx
  components/Cascader/panel/option.tsx
  components/Cascader/panel/search-panel.tsx
Labels: ✨ feature

#2137 fix(Image): error caused by JSON.stringfy a object with ReactNode as property value
  components/Image/image.tsx
Labels: 🐛 bug

#2111 fix(button): If the button is disabled, the click event should not ta…
  components/Button/index.tsx
Labels: 🐛 bug

#2187 enhance(Image): avoid 404 error when src is undefined
  components/Image/image.tsx
Labels: 🐛 bug

#2188 fix(Table): the second parameter of the render function is undefined
  components/Table/__test__/components.test.tsx
  components/Table/tbody/td.tsx
  components/Table/utils.tsx
Labels: 🐛 bug

#2171 style(table): fix the blank state style when setting scrollX
  components/Table/style/index.less
Labels: 💅 component style

#2186 fix(List): pagination's dropdown is hidden caused by list wrapper's [overflow: hidden] style
  components/List/style/index.less
Labels: 🐛 bug
