Repository arco-design/arco-design, pull requests merged in 2023-02, with the labels that each got.

#1728 fix: collapse onChange is called twice when header icon or title is clicked due to bubbling
  components/Collapse/__test__/index.test.tsx
  components/Collapse/item.tsx
Labels: 🐛 bug

#1748 style(Checkbox): icon color of disabled-checked Checkbox
  components/Checkbox/style/token.less
Labels: 💅 component style

#1751 fix: Cascader keydown event
  components/Cascader/cascader.tsx
  components/Cascader/interface.ts
  components/Cascader/panel/list.tsx
  components/Cascader/panel/search-panel.tsx
Labels: 🐛 bug

#1747 enhance: optimize Select UI jittering while searching/creating options
  components/Select/select.tsx
  components/Trigger/index.tsx
  components/Trigger/interface.ts
Labels: ⚡️ enhancement

#1750 fix: clickToClose not work in hover & props.style invalid
  components/Checkbox/README.en-US.md
  components/Checkbox/README.zh-CN.md
  components/Form/README.en-US.md
  components/Form/README.zh-CN.md
  components/Image/README.en-US.md
  components/Image/README.zh-CN.md
  components/Popconfirm/README.en-US.md
  components/Popconfirm/README.zh-CN.md
  components/Trigger/README.en-US.md
  components/Trigger/README.zh-CN.md
  components/Trigger/__demo__/basic.md
  components/Trigger/__test__/index.test.tsx
  components/Trigger/index.tsx
  components/Trigger/interface.ts
  components/Typography/README.en-US.md
  components/Typography/README.zh-CN.md
Labels: 🐛 bug

#1739 fix: the inline-block element causes the tree to produce an unnecessa…
  components/Tree/style/index.less
Labels: ⚡️ enhancement

#1765 style(Transfer): icon-drag style of Transfer item
  components/Transfer/__test__/__snapshots__/demo.test.ts.snap
  components/Transfer/item.tsx
Labels: 💅 component style

#1766 fix: In the simple ellipsis scene, resize cannot update the status
  components/Typography/base.tsx
  components/Typography/useEllipsis.tsx
  stories/Typography.story.tsx
Labels: 🐛 bug

#1767 fix(Upload): bulk upload files do not take effect in strict mode unde…
  components/Upload/__demo__/uploadList.md
  components/Upload/__test__/__snapshots__/demo.test.ts.snap
  components/Upload/interface.tsx
  components/Upload/upload.tsx
  components/Upload/uploader.tsx
Labels: 🐛 bug

#1764 fix(InputTag): property validate not work for value updating caused by tokenSeparators
  components/InputTag/__test__/index.test.tsx
  components/InputTag/input-tag.tsx
Labels: 🐛 bug

#1774 fix(InputTag): value format of onChange callback when validate result for tokenSeperators is not boolean
  components/InputTag/__test__/index.test.tsx
  components/InputTag/input-tag.tsx
Labels: 🐛 bug

#1783 fix: 修复[Upload]: duplicate uid警告出现的时机
  components/Upload/upload.tsx
Labels: 🐛 bug

#1786 feat: Input,select,datepicker,timepicker,cascader,treee-select,autocomplete supports status="warning"
  components/AutoComplete/README.en-US.md
  components/AutoComplete/README.zh-CN.md
  components/AutoComplete/index.tsx
  components/AutoComplete/interface.ts
  components/Cascader/README.en-US.md
  components/Cascader/README.zh-CN.md
  components/Cascader/__demo__/basic.md
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/DatePicker/README.en-US.md
  components/DatePicker/README.zh-CN.md
  components/DatePicker/__demo__/status.md
  components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
  components/DatePicker/interface.tsx
  components/DatePicker/picker-range.tsx
  components/DatePicker/picker.tsx
  components/Input/README.en-US.md
  components/Input/README.zh-CN.md
  components/Input/__demo__/status.md
  components/Input/__test__/__snapshots__/demo.test.ts.snap
  components/Input/input-element.tsx
  components/Input/input.tsx
  components/Input/interface.tsx
  components/Input/style/index.less
  components/Input/style/status.less
  components/Input/style/token.less
  components/Input/textarea.tsx
  components/InputTag/README.en-US.md
  components/InputTag/README.zh-CN.md
  components/InputTag/__demo__/basic.md
  components/InputTag/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/input-tag.tsx
  components/InputTag/interface.ts
  components/InputTag/style/index.less
  components/InputTag/style/token.less
  components/Mentions/README.en-US.md
  components/Mentions/README.zh-CN.md
  components/Select/README.en-US.md
  components/Select/README.zh-CN.md
  components/Select/__demo__/basic.md
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/Select/style/mixin.less
  components/Select/style/token.less
  components/TimePicker/README.en-US.md
  components/TimePicker/README.zh-CN.md
  components/TimePicker/__demo__/status.md
  components/TimePicker/__test__/__snapshots__/demo.test.ts.snap
  components/TimePicker/interface.tsx
  components/TimePicker/picker.tsx
  components/TreeSelect/README.en-US.md
  components/TreeSelect/README.zh-CN.md
  components/_class/picker/input-range.tsx
  components/_class/picker/input.tsx
  components/_class/picker/style/index.less
  components/_class/picker/style/status.less
  components/_class/picker/style/token.less
  components/_class/select-view.tsx
Labels: ✨ feature

#1787 fix: There is a problem with fixed columns when data is dynamically l…
  components/Table/table.tsx
  stories/Table.story.tsx
Labels: 🐛 bug

#1788 enhance(Select): update option created by user-inputting if props.options contain the same value option
  components/Select/__test__/index.test.tsx
  components/Select/utils.tsx
Labels: ⚡️ enhancement

#1784 fix(InputTag): validate function will trigger twice while pasting if it validate result not pass
  components/InputTag/__test__/index.test.tsx
  components/InputTag/input-tag.tsx
Labels: 🐛 bug
