Repository arco-design/arco-design, pull requests merged in 2023-07, with the labels that each got.

#2083 fix: Cascader onBlur
  components/Cascader/style/index.less
Labels: 🐛 bug

#2084 style(Input): Input width change after hovering due to clear icon
  components/Input/style/index.less
Labels: 💅 component style

#2093 fix: tabs resize throttle
  components/Tabs/tab-header/index.tsx
Labels: 🐛 bug

#2092 enhance(Select): judgement about whether to enable virtual list
  components/Select/select.tsx
  stories/Select.story.tsx
Labels: ⚡️ enhancement

#2096 fix(modal): clear wrapper dom after close modal(unmountOnExit=true)
  components/Modal/__test__/index.test.tsx
  components/Modal/modal.tsx
Labels: 🐛 bug

#2091 feat(Dropdown): add [popupVisible/defaultPopupVisible/getPopupContainer] properties for Dropdown.Button
  components/Dropdown/README.en-US.md
  components/Dropdown/README.zh-CN.md
  components/Dropdown/button.tsx
  components/Dropdown/interface.ts
Labels: ✨ feature

#2098 fix: radio和checkbox因为&&短路使得label缺少prefix-text包裹，而导致在暗黑模式下显示为黑色
  components/Checkbox/checkbox.tsx
  components/Radio/radio.tsx
Labels: 🐛 bug

#2066 fix(Table): use element.getBoundingClientRect().width to get the table width
  components/Table/table.tsx
Labels: ⚡️ enhancement

#2109 style: update Typography editable style
  components/Descriptions/README.en-US.md
  components/Descriptions/README.zh-CN.md
  components/Form/README.en-US.md
  components/Form/README.zh-CN.md
  components/Mentions/README.en-US.md
  components/Mentions/README.zh-CN.md
  components/Typography/__demo__/operations.md
  components/Typography/__test__/__snapshots__/demo.test.ts.snap
  components/Typography/base.tsx
  components/Typography/edit-content.tsx
  components/Typography/interface.tsx
  components/Typography/style/index.less
Labels: 🐛 bug
