Repository arco-design/arco-design, pull requests merged in 2023-03, with the labels that each got.

#1807 fix(Select): make sure Select option has height when its label is empty string
  components/Select/option.tsx
Labels: 🐛 bug

#1808 fix: the `onClick` injected by the `Trigger` component when `trigger=…
  components/Modal/__demo__/useModal.md
  components/Trigger/index.tsx
Labels: 🐛 bug

#1815 fix: form value should keep equal when rerender
  components/Form/__demo__/custom.md
  components/Form/__test__/case.test.tsx
  components/Form/context.ts
  components/Form/control.tsx
Labels: 🐛 bug

#1814 fix: not change show dates when click panel date
  components/DatePicker/picker-range.tsx
Labels: ⚡️ enhancement

#1809 fix: The bug that the scaling error occurs after ResizeBox.Split sets…
  components/ResizeBox/__test__/index.test.tsx
  components/ResizeBox/split.tsx
  stories/Resizebox.story.tsx
Labels: 🐛 bug

#1813 enhc(Avatar): Image child judgement
  components/Avatar/avatar.tsx
Labels: ⚡️ enhancement

#1810 enhance(InputNumber): disable BigInt usage in low-version browsers
  components/InputNumber/Decimal.ts
  components/InputNumber/index.tsx
  components/InputNumber/utils.ts
Labels: ⚡️ enhancement

#1816 style: fix table style & badge fontSize
  components/Badge/style/token.less
  components/Table/style/index.less
  components/Table/style/token.less
Labels: 💅 component style

#1829 enhancement: image preview supports mousewheel
  components/Image/image-preview.tsx
Labels: ⚡️ enhancement

#1843 feat(Select): add scrollIntoView method for SelectHandle
  components/Select/README.en-US.md
  components/Select/README.zh-CN.md
  components/Select/interface.tsx
  components/Select/select.tsx
Labels: ✨ feature

#1801 feat: add gird layout
  components/ConfigProvider/README.en-US.md
  components/ConfigProvider/README.zh-CN.md
  components/ConfigProvider/interface.ts
  components/Grid/README.en-US.md
  components/Grid/README.zh-CN.md
  components/Grid/__demo__/grid-responsive.md
  components/Grid/__demo__/grid.md
  components/Grid/__test__/__snapshots__/demo.test.ts.snap
  components/Grid/context.ts
  components/Grid/grid-item.tsx
  components/Grid/grid.tsx
  components/Grid/hooks/useResponsiveState.ts
  components/Grid/index.tsx
  components/Grid/interface.ts
  components/Grid/style/grid.less
  components/Grid/style/index.less
  components/Grid/utils.ts
Labels: ✨ feature

#1845 style: modify switch token prefix
  .github/workflows/deploy-site-preview.yml
  components/Switch/style/token.less
Labels: 🐛 bug

#1849 fix(tree-select): close icon not work when treeCheckedStrategy=all
  components/TreeSelect/__test__/index.test.tsx
  components/TreeSelect/tree-select.tsx
Labels: 🐛 bug

#1847 feat: treeselect supports renderFormat
  .github/workflows/deploy-site-preview.yml
  components/TreeSelect/__demo__/renderFormat.md
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/__test__/index.test.tsx
  components/TreeSelect/interface.ts
  components/TreeSelect/tree-select.tsx
Labels: ✨ feature

#1853 fix(style): Tabs card header-position border
  components/Tabs/style/index.less
  components/Tabs/style/vertical.less
  stories/Tabs.story.tsx
Labels: 💅 component style

#1863 fix: InputTag height jittering caused by input element width change
  components/Input/input-element.tsx
  components/Transfer/__demo__/with-table.md
Labels: 🐛 bug

#1865 fix: Table fix using group columns and colSpan together
  components/Table/hooks/useColumns.tsx
  stories/Table.story.tsx
Labels: 🐛 bug

#1884 enhance(Form): set default value of Form Context
  components/Form/context.ts
  components/Form/hooks/useContext.ts
  components/Form/store.tsx
Labels: ⚡️ enhancement

#1883 enhance: Table fixed columns can use string px
  components/Table/__test__/fixed-columns.test.tsx
  components/Table/hooks/useStickyOffsets.ts
  components/Table/utils.tsx
Labels: ⚡️ enhancement
