Repository arco-design/arco-design, pull requests merged in 2023-05, with the labels that each got.

#1955 fix: xxxl in grid not work
  components/Grid/__demo__/grid-responsive.md
  components/Grid/hooks/useResponsiveState.ts
  components/Grid/interface.ts
Labels: 🐛 bug

#1948 fix(Select): error caused by input large-size text to Select input box
  components/_util/getHighlightText.tsx
Labels: 🐛 bug

#1953 fix(Table): Fixed defaultExpandAllRows property not taking effect
  components/Table/hooks/useExpand.tsx
  stories/Table.story.tsx
Labels: 🐛 bug

#1962 fix: add throttle logic to ResizeObserver
  components/DatePicker/__test__/date.test.tsx
  components/List/__test__/index.test.tsx
  components/ResizeBox/__test__/group.test.tsx
  components/_class/VirtualList/__test__/index.test.tsx
  components/_util/resizeObserver.tsx
  stories/Resizebox.story.tsx
  tests/mockRAF.ts
  tests/setup.js
Labels: ⚡️ enhancement

#1942 chore: turkish locale
  components/locale/tr-TR.js
Labels: ✨ feature

#1963 style: use prefix vars to replace arco
  components/_class/Draggable/style/index.less
Labels: 🐛 bug

#1964 feat: popove & popconfirm support function content property
  components/Grid/README.en-US.md
  components/Grid/README.zh-CN.md
  components/Popconfirm/README.en-US.md
  components/Popconfirm/README.zh-CN.md
  components/Popconfirm/index.tsx
  components/Popconfirm/interface.ts
  components/Popover/README.en-US.md
  components/Popover/README.zh-CN.md
  components/Popover/index.tsx
  components/Popover/interface.ts
  components/Table/README.en-US.md
  components/Table/README.zh-CN.md
  components/TreeSelect/README.en-US.md
  components/TreeSelect/README.zh-CN.md
Labels: ✨ feature

#1961 fix: DatePicker disabledDate in quick selection
  components/DatePicker/__demo__/disabled-date.md
  components/DatePicker/panels/body.tsx
  components/DatePicker/panels/date/index.tsx
  components/DatePicker/panels/month/index.tsx
  components/DatePicker/panels/quarter/index.tsx
  components/DatePicker/panels/year/index.tsx
  components/DatePicker/util.ts
Labels: 🐛 bug

#1957 feat: index file update gridprops
  components/index.tsx
Labels: ⚡️ enhancement

#1960 feat(Select): support HTML id property
  components/Form/__test__/__snapshots__/demo.test.ts.snap
  components/_class/select-view.tsx
Labels: ✨ feature

#1976 fix(Image): Image not update after Image.previewProps updated
  components/Image/image.tsx
Labels: 🐛 bug

#1977 fix: popupZIndex invalid in drawer
  components/Drawer/index.tsx
  components/Modal/__test__/popup.test.tsx
  components/Modal/modal.tsx
Labels: ⚡️ enhancement

#1990 fix: pressenter should not be excuted when click search button
  components/Input/__test__/index.test.tsx
  components/Input/search.tsx
Labels: 🐛 bug

#1989 fix(Pagination): pagesize illegal scene
  components/Pagination/__test__/index.test.tsx
  components/Pagination/pagination.tsx
Labels: 🐛 bug

#1991 style(Menu): ensure that icon of menu item is horizontal-center after Menu collapsed
  components/Menu/style/index.less
Labels: 💅 component style

#1993 enhance: remove value of <input/> in SelectView if it is hidden
  components/BackTop/__test__/__snapshots__/demo.test.ts.snap
  components/Calendar/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/__test__/__snapshots__/demo.test.ts.snap
  components/Cascader/__test__/index.test.tsx
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
  components/Input/__test__/__snapshots__/demo.test.ts.snap
  components/Pagination/__test__/__snapshots__/demo.test.ts.snap
  components/Select/__test__/__snapshots__/demo.test.ts.snap
  components/Select/__test__/index.test.tsx
  components/Table/__test__/__snapshots__/demo.test.ts.snap
  components/TimePicker/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
  components/TreeSelect/__test__/index.test.tsx
  components/_class/select-view.tsx
Labels: ⚡️ enhancement

#1988 fix(Input.TextArea): TextArea autoResize not work while composition updating
  components/Input/textarea.tsx
Labels: 🐛 bug

#1992 fix: DatePicker input error when set timezone or utcOffset
  components/DatePicker/picker.tsx
Labels: 🐛 bug
