Repository arco-design/arco-design, pull requests merged in 2024-01, with the labels that each got.

#2477 fix: breadcrumb show extra separator
  components/Breadcrumb/index.tsx
Labels: 🐛 bug

#2474 fix(Table): Fix the issue where the loading configuration does not ta…
  components/Table/__test__/index.test.tsx
  components/Table/table.tsx
  stories/Table.story.tsx
Labels: 🐛 bug

#2480 fix: Space items wrap with fragment
  components/Space/__test__/index.test.tsx
  components/Space/index.tsx
  components/Space/toArray.ts
  package.json
  yarn.lock
Labels: 🐛 bug

#2484 fix(Select): unexpected infinite loop in single mode while allowCreat…
  components/Select/select.tsx
Labels: 🐛 bug

#2489 fix: image previewProps
  components/Image/image-preview-group.tsx
  stories/Image.story.tsx
Labels: 🐛 bug

#2490 doc(AutoComplete): add a new demo for filterOption usage
  components/AutoComplete/__demo__/custom-search.md
  components/AutoComplete/__test__/__snapshots__/demo.test.ts.snap
Labels: 📖 documentation

#2505 enhance: form resetFields when get a number or symbol as argument
  components/Form/store.tsx
Labels: 🐛 bug

#2504 enhance: Popover hide when content is empty
  components/Popover/index.tsx
  components/Tooltip/index.tsx
  components/_util/is.ts
Labels: ⚡️ enhancement

#2494 feat: add data color list
  components/Trigger/getPopupStyle.ts
  components/style/theme/color/colors.less
  components/style/theme/color/css-variables.less
  components/style/theme/css-variables.less
  components/style/theme/global.less
  site/src/pages/token/tokens.js
Labels: ✨ feature

#2503 feat(InputTag): add new property maxTagCount
  components/InputTag/README.en-US.md
  components/InputTag/README.zh-CN.md
  components/InputTag/__demo__/max-tag-count.md
  components/InputTag/__test__/__snapshots__/demo.test.ts.snap
  components/InputTag/input-tag.tsx
  components/InputTag/interface.ts
  components/InputTag/style/index.less
Labels: ✨ feature

#2501 enhance(InputNumber): initial value while clicking plus/minus button
  components/InputNumber/index.tsx
Labels: ⚡️ enhancement

#2502 feat: trigger supports boundaryDistance
  components/ConfigProvider/README.en-US.md
  components/ConfigProvider/README.zh-CN.md
  components/Image/README.en-US.md
  components/Image/README.zh-CN.md
  components/Trigger/README.en-US.md
  components/Trigger/README.zh-CN.md
  components/Trigger/__demo__/boundaryDistance.md
  components/Trigger/__test__/__snapshots__/demo.test.ts.snap
  components/Trigger/getPopupStyle.ts
  components/Trigger/index.tsx
  components/Trigger/interface.ts
Labels: ✨ feature

#2488 fix(typography): fix throttle problem
  components/Typography/base.tsx
  components/_util/throttleByRafV2.ts
Labels: 🐛 bug

#2516 feat: DatePicker add inputProps
  components/DatePicker/README.en-US.md
  components/DatePicker/README.zh-CN.md
  components/DatePicker/__test__/range.test.tsx
  components/DatePicker/interface.tsx
  components/DatePicker/picker-range.tsx
  components/_class/picker/input-range.tsx
  stories/DatePicker.story.tsx
Labels: ✨ feature
