Repository arco-design/arco-design, pull requests merged in 2024-03, with the labels that each got.

#2550 fix(image): when src change，set loading
  components/Image/image.tsx
Labels: 🐛 bug

#2570 style(Select): change font size of Select with size:large to 14px
  components/Select/style/token.less
Labels: 💅 component style

#2553 enhance(Table): support expanedRows and treeData while Table is virtualized
  components/Table/__demo__/virtualized.md
  components/Table/style/index.less
  components/Table/tbody/index.tsx
  components/Table/tbody/tr.tsx
Labels: ⚡️ enhancement

#2592 fix(Table): React unique-key warning caused by TBody
  components/Table/tbody/index.tsx
Labels: 🐛 bug

#2596 feat: update expandable
  components/Typography/__demo__/ellipsis-basic.md
  components/Typography/__test__/__snapshots__/demo.test.ts.snap
  components/Typography/ellipsis.tsx
  components/Typography/interface.tsx
Labels: ✨ feature

#2593 feat: add disableTranslateCorrection
  components/Image/image-preview.tsx
  components/Image/interface.ts
Labels: ✨ feature

#2562 feat(config-provider): add effectGlobalModal prop
  components/ConfigProvider/README.en-US.md
  components/ConfigProvider/README.zh-CN.md
  components/ConfigProvider/__demo__/local-setting.md
  components/ConfigProvider/__demo__/modal-setting.md
  components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
  components/ConfigProvider/index.tsx
  components/ConfigProvider/interface.ts
  components/index.tsx
Labels: ✨ feature

#2594 feat: slider supports multiple points
  .github/workflows/deploy-site-preview.yml
  components/Slider/__demo__/input.md
  components/Slider/__demo__/marks.md
  components/Slider/__demo__/range-multi.md
  components/Slider/__test__/__snapshots__/demo.test.ts.snap
  components/Slider/dots.tsx
  components/Slider/hooks/useLegalValue.ts
  components/Slider/index.tsx
  components/Slider/interface.tsx
  components/Slider/ticks.tsx
  components/Slider/utils.ts
Labels: ✨ feature

#2606 fix: input autowidth fix
  components/Input/style/index.less
Labels: 🐛 bug

#2591 fix: can not use suffix and addAfter prop in input-search
  components/AutoComplete/index.tsx
  components/Input/search.tsx
Labels: 🐛 bug

#2602 fix: wrong fixedClassName
  components/Table/table.tsx
Labels: 🐛 bug
